#!/usr/bin/env python3
# Homage fan game. Not an official Marvel, Sony or Insomniac game; no affiliation.
# Writes <round>/SHOTLIST.md from the replayed input scripts and the captured telemetry (neutral: what was pressed,
# camera settings, measured ranges; no assessment).  usage: make_shotlist.py <round dir> <round label> <commit>
import csv, glob, json, os, sys

ROUND, LABEL, COMMIT = sys.argv[1], sys.argv[2], sys.argv[3]
HERE = os.path.dirname(os.path.abspath(__file__))
SEQ = [
    ("a_swing_chain", "Swing chain down the avenue at speed",
     "Airborne start (spawn 22 m over the avenue with 22 m/s forward velocity), then a continuous swing chain along +X."),
    ("b_release_trick_dive_zip", "Release + trick + dive + zip to a rooftop",
     "Airborne start 58 m over the avenue (26 m/s forward), one swing, release, dive, web-zip to a podium roof edge, perch."),
    ("c_wallrun_perch", "Wall-run up a building + perch",
     "Street start facing a 40.9 m podium facade; sprint into the wall, wall-run to the top, land on the roof, camera turn, "
     "web-zip to the roof edge over the avenue, perch."),
    ("d_sprint_jump_first_swing", "Ground sprint -> jump -> first swing",
     "Street start; run down the avenue, charged jump, first swing, then the chain continues."),
]
FIELD = {"move": "stick (x right, y fwd)", "swing": "RMB swing", "jump": "Space", "sprint": "Shift", "zip": "E zip",
         "drop": "C drop/dive", "quick": "Q boost", "look": "look (deg/s yaw, pitch-down)", "heading": "heading (world yaw deg)"}


def fmt_key(k):
    parts = []
    for f, v in k.items():
        if f == "t":
            continue
        if f == "heading" and v is False:
            parts.append("heading off")
        elif isinstance(v, bool):
            parts.append(f"{FIELD.get(f, f)} {'down' if v else 'up'}")
        else:
            parts.append(f"{FIELD.get(f, f)} = {v}")
    return ", ".join(parts)


def stats(path):
    if not os.path.exists(path):
        return None
    rows = list(csv.DictReader(open(path)))
    if not rows:
        return None
    f = lambda k: [float(r[k]) for r in rows]
    sp, hf, fov, cd = f("speed_mps"), f("height_above_floor_m"), f("cam_vfov_deg"), f("cam_dist_m")
    modes = []
    for r in rows:
        keep = {"trick", "dive", "release", "zipPull", "pointLaunch", "wallRun", "crawl", "zipFlight", "perchLand", "landRoll",
                "landHard", "landMedium", "jumpLaunch", "wallJump"}
        m = f"{r['mode']}/{r['sub']}" if r["sub"] in keep else r["mode"]
        if not modes or modes[-1][0] != m:
            modes.append([m, float(r["t"])])
    tricks = sorted({r["trick"] for r in rows if r["trick"]})
    chain = max(int(r["chain"]) for r in rows)
    x0, x1 = float(rows[0]["x_m"]), float(rows[-1]["x_m"])
    return dict(n=len(rows), dur=float(rows[-1]["t"]), sp=(min(sp), max(sp)), hf=(min(hf), max(v for v in hf if v < 900)),
                fov=(min(fov), max(fov)), cd=(min(cd), max(cd)), modes=modes, tricks=tricks, chain=chain, dx=x1 - x0)


out = []
w = out.append
w(f"# Traversal (P3) — {LABEL} shot list")
w("")
w("> Homage fan game. Not an official Marvel, Sony or Insomniac game; no affiliation. Nothing here is meant to infringe.")
w("")
w(f"- Build: branch `night1/traversal`, commit `{COMMIT}`, UE 5.8.3, map `/Game/Tests/Traversal/Trav_Canyon` "
  "(generated by `unreal/WebHomage/Scripts/build_traversal.py`; layout in `docs/night1/traversal/trav_canyon_layout.json`).")
w("- Reproduce: `docs/night1/traversal/capture_round.sh <round dir>` (runs `unreal/WebHomage/Scripts/run_game.sh`, real `-game`, offscreen).")
w("- Game mode `AWebTravGameMode` -> pawn `AWebTravCharacter` (placeholder block figure; web strands = chain of thin cylinders).")
w("")
w("## Capture settings (all sequences)")
w("")
w("| | video | stills |")
w("|---|---|---|")
w("| output | 1920x1080, 60 fps, H.264 mp4 | 3840x2160, JPEG q92 (converted from PNG) |")
w("| internal resolution | 1920x1080 (`r.ScreenPercentage 100`) | 3840x2160 (`r.ScreenPercentage 100`) |")
w("| time step | fixed 1/60 s (`-benchmark -fps=60 -dumpmovie`) | fixed 1/60 s (`-benchmark -fps=60`) |")
w("| AA / GI | TSR, Lumen (project defaults) | same |")
w("")
w("The video frames are rendered offline at a fixed step; they say nothing about real-time frame rate.")
w("")
w("Camera (port of `src/player/camera.js`): chase camera, critically damped springs on every framing value; base vertical FOV 58 deg, "
  "target FOV = 58 + 13 x smoothstep(speed, 12, 44 m/s) + 5 while diving, plus launch-kick and impact-punch springs; "
  "distance targets 3.6-4.3 m swinging, 3.8-4.5 m air, 3.9-4.6 m ground, 4.8 m wall, 4.3 m perch; auto-recenter behind the swing "
  "plane / travel direction after 0.9 s without look input; trauma shake on landings, wall kicks, launches. "
  "The vertical FOV is converted to Unreal's horizontal FOV with the viewport aspect. Motion blur amount follows the "
  "browser's speed ramp (camera post-process override).")
w("")
w("Inputs are replayed from JSON (`docs/night1/traversal/scripts/`, `-WHTravScript=`), sampled once per frame and fed to the same "
  "code path as the keyboard / pad. `heading` = the stick is set every frame to the world direction given (yaw deg), expressed "
  "relative to the current camera. Swing button edges in sequences a and d were generated by a timing rule (release on the "
  "rising front of the arc, re-press once the upward speed has dropped) and then written out as plain timed keys "
  "(`scripts/bake_keys.py`; the `*_auto.json` files hold the rule form).")
w("")
w("Telemetry CSV columns (one row per rendered frame): frame, t, mode, sub, body position x/y/z (m, UE axes), velocity, speed, "
  "horizontal speed, height above the floor below, swing anchor x/y/z, rope length, web tension 0..1, momentum-chain level, "
  "trick, zip target present + position, camera position / yaw / pitch / vertical FOV / distance, motion-blur factor, input state.")
w("")
for name, title, desc in SEQ:
    js = json.load(open(os.path.join(HERE, "scripts", name + ".json")))
    st = stats(os.path.join(ROUND, name + "_telemetry.csv"))
    w(f"## {name} — {title}")
    w("")
    w(desc)
    w("")
    files = [f"`{name}.mp4`", f"`{name}_telemetry.csv`"] + [f"`stills/{os.path.basename(p)}`" for p in sorted(glob.glob(os.path.join(ROUND, "stills", name + "_*.jpg")))]
    w("Files: " + ", ".join(files))
    w("")
    sp = js["spawn"]
    w(f"Spawn: position {sp['pos']} m, yaw {sp.get('yaw', 0)} deg, camera pitch {sp.get('camPitch', 0.14)} rad"
      + (f", initial velocity {sp['vel']} m/s" if "vel" in sp else "") + f". Script: `scripts/{name}.json`.")
    w("")
    w("| t (s) | input change |")
    w("|---|---|")
    for k in js["keys"]:
        w(f"| {float(k['t']):.3f} | {fmt_key(k)} |")
    w("")
    if st:
        w(f"Measured over the video ({st['n']} frames, {st['dur']:.2f} s): speed {st['sp'][0]:.1f}-{st['sp'][1]:.1f} m/s; height above the "
          f"floor {st['hf'][0]:.1f}-{st['hf'][1]:.1f} m; X travelled {st['dx']:.0f} m; vertical FOV {st['fov'][0]:.1f}-{st['fov'][1]:.1f} deg; "
          f"camera distance {st['cd'][0]:.1f}-{st['cd'][1]:.1f} m; max momentum-chain level {st['chain']}; tricks: {', '.join(st['tricks']) or 'none'}.")
        w("")
        w("State sequence (mode/sub-state, start time s): " + " -> ".join(f"{m} {t:.2f}" for m, t in st["modes"]))
        w("")
open(os.path.join(ROUND, "SHOTLIST.md"), "w").write("\n".join(out) + "\n")
print("wrote", os.path.join(ROUND, "SHOTLIST.md"))
