#!/usr/bin/env python3
# Homage fan game. Not an official Marvel, Sony or Insomniac game; no affiliation.
# Writes <round>/SHOTLIST.md from the replayed input scripts and the captured telemetry (neutral: what was pressed,
# camera settings, measured ranges; no assessment).  usage: make_shotlist.py <round dir> <round label> <commit>
import csv, glob, json, os, sys

ROUND, LABEL, COMMIT = sys.argv[1], sys.argv[2], sys.argv[3]
HERE = os.path.dirname(os.path.abspath(__file__))
SEQ = [
    ("a_swing_chain", "Swing chain down the avenue at speed",
     "Airborne start (spawn 22 m over the avenue with 22 m/s forward velocity), then a continuous swing chain along +X."),
    ("b_release_trick_dive_zip", "Release + trick + dive + zip to a rooftop",
     "Airborne start 58 m over the avenue (26 m/s forward), one swing, release, dive, web-zip to a podium roof corner across the avenue, perch."),
    ("c_wallrun_perch", "Wall-run up a building + perch",
     "Street start facing a 40.9 m podium facade; sprint into the wall, wall-run to the top, land on the roof, camera turn, "
     "web-zip to the roof edge over the avenue, perch."),
    ("d_sprint_jump_first_swing", "Ground sprint -> jump -> first swing",
     "Street start; run down the avenue, charged jump, first swing, then the chain continues."),
]
FIELD = {"trick": "F trick", "move": "stick (x right, y fwd)", "swing": "RMB swing", "jump": "Space", "sprint": "Shift", "zip": "E zip",
         "drop": "C drop/dive", "quick": "Q boost", "look": "look (deg/s yaw, pitch-down)", "heading": "heading (world yaw deg)"}


def fmt_key(k):
    parts = []
    for f, v in k.items():
        if f == "t":
            continue
        if f == "heading" and v is False:
            parts.append("heading off")
        elif isinstance(v, bool):
            parts.append(f"{FIELD.get(f, f)} {'down' if v else 'up'}")
        else:
            parts.append(f"{FIELD.get(f, f)} = {v}")
    return ", ".join(parts)


def stats(path):
    if not os.path.exists(path):
        return None
    rows = list(csv.DictReader(open(path)))
    if not rows:
        return None
    f = lambda k: [float(r[k]) for r in rows]
    sp, hf, fov, cd = f("speed_mps"), f("height_above_floor_m"), f("cam_vfov_deg"), f("cam_dist_m")
    modes = []
    for r in rows:
        keep = {"trick", "dive", "release", "zipPull", "pointLaunch", "wallRun", "crawl", "zipFlight", "perchLand", "landRoll",
                "landHard", "landMedium", "jumpLaunch", "wallJump"}
        m = f"{r['mode']}/{r['sub']}" if r["sub"] in keep else r["mode"]
        if not modes or modes[-1][0] != m:
            modes.append([m, float(r["t"])])
    tricks = sorted({r["trick"] for r in rows if r["trick"]})
    chain = max(int(r["chain"]) for r in rows)
    x0, x1 = float(rows[0]["x_m"]), float(rows[-1]["x_m"])
    return dict(n=len(rows), dur=float(rows[-1]["t"]), sp=(min(sp), max(sp)), hf=(min(hf), max(v for v in hf if v < 900)),
                fov=(min(fov), max(fov)), cd=(min(cd), max(cd)), modes=modes, tricks=tricks, chain=chain, dx=x1 - x0)


out = []
w = out.append
w(f"# Traversal (P3) — {LABEL} shot list")
w("")
w("> Homage fan game. Not an official Marvel, Sony or Insomniac game; no affiliation. Nothing here is meant to infringe.")
w("")
w(f"- Build: branch `night1/traversal`, commit `{COMMIT}`, UE 5.8.3, map `/Game/Tests/Traversal/Trav_Canyon` "
  "(generated by `unreal/WebHomage/Scripts/build_traversal.py`; layout in `docs/night1/traversal/trav_canyon_layout.json`).")
w("- Reproduce: `docs/night1/traversal/capture_round.sh <round dir>` (runs `unreal/WebHomage/Scripts/run_game.sh`, real `-game`, offscreen).")
if LABEL.endswith("04"):
    w("- Game mode `AWebTravGameMode` -> pawn `AWebTravCharacter`. Hero: the browser build's GLB (`public/assets/spiderman.glb`, 58 bones, "
      "79 clips at 30 fps) imported by `build_traversal.py` into `/Game/Traversal/HeroDev` (dev proxy), animated by the C++ "
      "`UWebTravAnimInstance` (clip nodes with the browser's per-transition blend times, 3-way swing blend by arc phase, web-hand arm aimed "
      "at the anchor, air-phase clip timelines that differ from the previous cycle, procedural roll/pitch sway in the air, whole-body "
      "trick spins). Tricks happen only when the trick input is pressed. Web strands = chain of thin cylinders.")
else:
    w("- Game mode `AWebTravGameMode` -> pawn `AWebTravCharacter` (placeholder block figure; web strands = chain of thin cylinders).")
w("")
w("## Capture settings (all sequences)")
w("")
w("| | video | stills |")
w("|---|---|---|")
w("| output | 1920x1080, 60 fps, H.264 mp4 | 3840x2160, JPEG q92 (converted from PNG) |")
w("| internal resolution | 1920x1080 (`r.ScreenPercentage 100`) | 3840x2160 (`r.ScreenPercentage 100`) |")
w("| time step | fixed 1/60 s (`-benchmark -fps=60 -dumpmovie`) | fixed 1/60 s (`-benchmark -fps=60`) |")
w("| AA / GI | TSR, Lumen (project defaults) | same |")
w("")
w("The video frames are rendered offline at a fixed step; they say nothing about real-time frame rate.")
w("")
if LABEL.endswith("03") or LABEL.endswith("04"):
    w("Camera (round 03 chase camera): position 6.0 m behind the hero along the lagged heading yaw (browser auto-recenter behind "
      "the swing plane / travel direction), horizontal position spring 0.07 s then held 4.0-6.5 m away, height 2.4 m over the hero "
      "centre with a 0.05 s vertical spring, held 1.6-3.2 m above; 0.3 m right-shoulder offset. Orientation: yaw toward the hero; "
      "pitch set so the hero's screen centre sits at a framing target (0 top .. 1 bottom): while swinging 0.67 at the bottom of the "
      "arc to 0.36 at +-0.85 rad of rope angle; airborne 0.67 near the street to 0.36 at 40 m up; 0.22 s spring; pitch clamped 8-32 deg "
      "down. Collision: 0.22 m sphere sweeps from the hero's chest (or 1-2.6 m above it when the chest is against a surface); when "
      "the default spot is not clear, raised / rotated orbit spots are searched and eased in, with a cut when the camera would come "
      "within 4 m. Vertical FOV 58 + 13 x smoothstep(speed, 12, 44 m/s) + 5 diving, launch-kick / impact-punch springs, trauma shake, "
      "speed motion blur (browser values); vertical FOV converted to Unreal's horizontal FOV with the viewport aspect.")
else:
    w("Camera (port of `src/player/camera.js`): chase camera, critically damped springs on every framing value; base vertical FOV 58 deg, "
      "target FOV = 58 + 13 x smoothstep(speed, 12, 44 m/s) + 5 while diving, plus launch-kick and impact-punch springs.")
w("")
if os.path.exists(os.path.join(ROUND, "ANIM_CHECK.txt")):
    w("Animation check (T-pose / no-clip frames; air silhouettes sampled at 6 fps, pose signature = head / hands / feet relative to the "
      "hips in camera right / up; consecutive air cycles compared by node sequence): `ANIM_CHECK.txt` (`docs/night1/traversal/anim_check.py`).")
    w("")
if os.path.exists(os.path.join(ROUND, "CAM_CHECK.txt")):
    w("Per-frame camera / framing check (hero screen bbox height and centre-Y, in-frame flag, camera-hero distance, camera-in-geometry "
      "flag, camera pitch / height; min / max per sequence and hero screen travel per swing): `CAM_CHECK.txt` (`docs/night1/traversal/cam_check.py`).")
    w("")
w("Inputs are replayed from JSON (`docs/night1/traversal/scripts/`, `-WHTravScript=`), sampled once per frame and fed to the same "
  "code path as the keyboard / pad. `heading` = the stick is set every frame to the world direction given (yaw deg), expressed "
  "relative to the current camera. Swing button edges in sequences a and d were generated by a timing rule (release on the "
  "rising front of the arc, re-press once the upward speed has dropped) and then written out as plain timed keys "
  "(`scripts/bake_keys.py`; the `*_auto.json` files hold the rule form).")
w("")
if os.path.exists(os.path.join(ROUND, "DROP_TEST.txt")):
    w("Swing arc test output (per swing: height at the preceding release, low point, drop, rope length, duration, horizon travel on screen): `DROP_TEST.txt` "
      "(generated by `docs/night1/traversal/drop_test.py` from the telemetry CSVs of the videos).")
    w("")
w("Telemetry CSV columns (one row per rendered frame): frame, t, mode, sub, body position x/y/z (m, UE axes), velocity, speed, "
  "horizontal speed, height above the floor below, swing anchor x/y/z, rope length, web tension 0..1, momentum-chain level, "
  "trick, zip target present + position, camera position / yaw / pitch / vertical FOV / distance, motion-blur factor, input state.")
w("")
for name, title, desc in SEQ:
    js = json.load(open(os.path.join(HERE, "scripts", name + ".json")))
    st = stats(os.path.join(ROUND, name + "_telemetry.csv"))
    w(f"## {name} — {title}")
    w("")
    w(desc)
    w("")
    files = [f"`{name}.mp4`", f"`{name}_telemetry.csv`"] + [f"`stills/{os.path.basename(p)}`" for p in sorted(glob.glob(os.path.join(ROUND, "stills", name + "_*.jpg")))]
    w("Files: " + ", ".join(files))
    w("")
    sp = js["spawn"]
    w(f"Spawn: position {sp['pos']} m, yaw {sp.get('yaw', 0)} deg, camera pitch {sp.get('camPitch', 0.14)} rad"
      + (f", initial velocity {sp['vel']} m/s" if "vel" in sp else "") + f". Script: `scripts/{name}.json`.")
    w("")
    w("| t (s) | input change |")
    w("|---|---|")
    for k in js["keys"]:
        w(f"| {float(k['t']):.3f} | {fmt_key(k)} |")
    w("")
    if st:
        w(f"Measured over the video ({st['n']} frames, {st['dur']:.2f} s): speed {st['sp'][0]:.1f}-{st['sp'][1]:.1f} m/s; height above the "
          f"floor {st['hf'][0]:.1f}-{st['hf'][1]:.1f} m; X travelled {st['dx']:.0f} m; vertical FOV {st['fov'][0]:.1f}-{st['fov'][1]:.1f} deg; "
          f"camera distance {st['cd'][0]:.1f}-{st['cd'][1]:.1f} m; max momentum-chain level {st['chain']}; tricks: {', '.join(st['tricks']) or 'none'}.")
        w("")
        w("State sequence (mode/sub-state, start time s): " + " -> ".join(f"{m} {t:.2f}" for m, t in st["modes"]))
        w("")
open(os.path.join(ROUND, "SHOTLIST.md"), "w").write("\n".join(out) + "\n")
print("wrote", os.path.join(ROUND, "SHOTLIST.md"))
