// Generates the UE terrain shader include from the browser's park / lawn GLSL (single source of truth: src/world/ground.js createGrassMaterial).
//   node tools/export/gen_terrain_shaders.mjs  ->  unreal/WebHomage/Shaders/Terrain/Park.ush
// Same machinery as tools/export/gen_shaders.mjs (piece A owns that one; this file only ADDS the terrain include): GLSL snippets are cut out of the
// three.js onBeforeCompile templates, template placeholders are evaluated for the two variants (park / coast lawn), translated by glsl2hlsl.mjs and
// wrapped in UE entry points. Frames: browser frame (metres, y up) inside, UE frame (cm, Z up) at the entry points. Data constants (meadows, ponds)
// come from Shaders/Terrain/ParkData.ush, written by tools/terrain/prep_terrain.py from the export.
import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
import { translate, PRELUDE } from './glsl2hlsl.mjs';

const ROOT = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '../..');
const OUT = path.join(ROOT, 'unreal/WebHomage/Shaders/Terrain');
fs.mkdirSync(OUT, { recursive: true });
const js = fs.readFileSync(path.join(ROOT, 'src/world/ground.js'), 'utf8');
const fnSrc = js.slice(js.indexOf('export function createGrassMaterial'), js.indexOf("mat.customProgramCacheKey = () => 'city-grass"));
const cut = (s, a, b, from = 0) => { const i = s.indexOf(a, from); if (i < 0) throw new Error('marker not found: ' + a); const j = s.indexOf(b, i + a.length); if (j < 0) throw new Error('end marker not found: ' + b); return [s.slice(i + a.length, j), j]; };

const [declRaw] = cut(fnSrc, "sh.fragmentShader = sh.fragmentShader.replace('#include <common>', `#include <common>", '`)');
const [mapRaw] = cut(fnSrc, ".replace('#include <map_fragment>', `{", '}`)');   // the block body (without the outer braces)
const evalT = (raw, opts) => new Function('md', 'pw', 'opts', 'return `' + raw.replace(/\\/g, '\\\\') + '`')(new Array(11).fill(0), new Array(5).fill(0), opts);

const TEX = ['tCol', 'tNoise'];
const texDecl = TEX.map(n => `Texture2D ${n}, SamplerState ${n}Sampler`).join(', '), texPass = TEX.map(n => `${n}, ${n}Sampler`).join(', ');

// ---- shared helpers (pondD / pkFld / ellD): uniforms are provided by ParkData.ush
function variant(name, opts) {
  let body = evalT(mapRaw, opts);
  // the GLSL block starts with 'vec2 p = vWP.xz;' and ends with 'diffuseColor.rgb = c;': turn it into a function of p
  if (!/vec2 p = vWP\.xz;/.test(body) || !/diffuseColor\.rgb = c;/.test(body)) throw new Error('map block anchors changed');
  body = body.replace('vec2 p = vWP.xz;', '').replace('diffuseColor.rgb = c;', 'return c;');
  return `vec3 ${name}(vec2 p) {\n${body}\n}`;
}
// one translation unit: every user function (helpers + both variants) must be known to the translator to thread the texture parameters through the call sites
const translated = translate(evalT(declRaw, { lawn: false }) + '\n' + variant('terrainPark', { lawn: false }) + '\n' + variant('terrainLawn', { lawn: true }), { textures: TEX });

const ush = `// GENERATED by tools/export/gen_terrain_shaders.mjs from src/world/ground.js (createGrassMaterial) -- do not edit by hand.
// Fan homage project; not an official Marvel / Sony / Insomniac product, no affiliation.
#pragma once
#include "/Project/Terrain/ParkData.ush"

#define TEXDECL ${texDecl}
#define TEXPASS ${texPass}
${PRELUDE}
float3 CityB2U(float3 v) { return float3(v.x, v.z, v.y); }            // browser frame -> UE frame (unit-free directions)

${translated}

// shading height field: gentle rolling ground (knolls / hollows of 0.6-1.5 m over 40-160 m), the lawn normal follows it (browser: normal_fragment_maps block)
float TerrainGH(TEXDECL, float2 q) { return Texture2DSampleLevel(tNoise, tNoiseSampler, fl2(q / 160.0f + float2(0.27f, 0.61f)), 0.0f).g * 1.5f + Texture2DSampleLevel(tNoise, tNoiseSampler, fl2(q / 45.0f + float2(0.83f, 0.13f)), 0.0f).r * 0.6f; }
float3 TerrainNormalB(TEXDECL, float2 p) {   // browser-frame normal (y up)
  float e = 3.0f;
  float dx = (TerrainGH(TEXPASS, p + float2(e, 0.0f)) - TerrainGH(TEXPASS, p - float2(e, 0.0f))) / (2.0f * e);
  float dz = (TerrainGH(TEXPASS, p + float2(0.0f, e)) - TerrainGH(TEXPASS, p - float2(0.0f, e))) / (2.0f * e);
  return normalize(float3(-dx * 6.0f, 1.0f, -dz * 6.0f));
}

// UE entry points. wposU = UE world position (cm). rough / nU (UE-frame world normal, mixed 0.85 toward the height-field normal as in the browser).
float3 TerrainParkEntry(TEXDECL, float3 wposU, float lawn, out float rough, out float3 nU)
{
  float2 p = float2(wposU.x, wposU.y) * 0.01f;
  float3 c = lawn > 0.5f ? terrainLawn(TEXPASS, p) : terrainPark(TEXPASS, p);
  float3 nb = normalize(lerp(float3(0.0f, 1.0f, 0.0f), TerrainNormalB(TEXPASS, p), 0.85f));
  nU = CityB2U(nb); rough = 0.95f;
  return c;
}
`;
fs.writeFileSync(path.join(OUT, 'Park.ush'), ush);
console.log('Park.ush', ush.length, 'bytes');
