// Generates the UE material include files from the browser city's GLSL (single source of truth: src/world/*.js).
//   node tools/export/gen_shaders.mjs  ->  unreal/WebHomage/Shaders/City/{Facade,Detail,Roof,Asphalt,Sidewalk}.ush
// The Custom nodes of /Game/City/Materials/M_City* include them as "/Project/City/<name>.ush" (UE maps
// <project>/Shaders to /Project). Frames: every function works in the BROWSER frame (metres, y up); the entry points
// take UE-frame inputs and convert: browser (x, y, z) = UE (X, Z, Y) / 100.
import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
import { translate, PRELUDE } from './glsl2hlsl.mjs';

const ROOT = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '../..');
const OUT = path.join(ROOT, 'unreal/WebHomage/Shaders/City');
fs.mkdirSync(OUT, { recursive: true });
const src = (f) => fs.readFileSync(path.join(ROOT, 'src/world', f), 'utf8');
const between = (s, a, b) => { const i = s.indexOf(a); if (i < 0) throw new Error('marker not found: ' + a); const j = s.indexOf(b, i + a.length); return s.slice(i + a.length, j); };
const HDR = (what) => `// GENERATED by tools/export/gen_shaders.mjs from src/world/${what} -- do not edit by hand.
// Fan homage project; not an official Marvel / Sony / Insomniac product, no affiliation.
#pragma once
`;
const texMacros = (list) => {
  const decl = list.map(([n, arr]) => `${arr ? 'Texture2DArray' : 'Texture2D'} ${n}, SamplerState ${n}Sampler`).join(', ');
  const pass = list.map(([n]) => `${n}, ${n}Sampler`).join(', ');
  return { decl, pass };
};
const B2U = `
float3 CityB2U(float3 v) { return float3(v.x, v.z, v.y); }            // browser frame -> UE frame (unit-free directions)
float3 CityU2B(float3 v) { return float3(v.x, v.z, v.y); }            // UE frame -> browser frame
`;

// ------------------------------------------------------------------ facade
{
  const js = src('facade.js');
  const glsl = between(js, 'const FRAG_DECL = /* glsl */`', '`;');
  const TEX = [['tWallC', 1], ['tWallN', 1], ['tWallH', 1], ['tDetail', 0], ['tInterior', 0], ['tSigns', 0], ['tNoise', 0]];
  const { decl, pass } = texMacros(TEX);
  const body = translate(glsl, { arrays: new Set(TEX.filter(t => t[1]).map(t => t[0])), textures: TEX.map(t => t[0]) })
    .replace(/\bR \* (vFac|gDx|gDy)\b/g, 'mul($1, R)'); // GLSL mat2 * vec (column-major) == HLSL mul(vec, float2x2(same list))
  const ush = `${HDR('facade.js (FRAG_DECL)')}
#define TEXDECL ${decl}
#define TEXPASS ${pass}
${PRELUDE}${B2U}
// varyings / uniforms of the browser shader (set by CityFacade)
static float2 vFac; static float4 vF; static float4 vS; static float4 vW; static float4 vX; static float3 vTint;
static float3 vWPos; static float3 vWN; static float3 gCamPos; static float2 gFragCoord;
static float uInteriorGain = 0.5; static float uShopGain = 0.7; static float uNightK = 0.0; static float uDnTime = 0.0;
${body}
// ---- UE entry. fac = UV0; F = (UV1, UV2); S = (UV3, UV4); W = (UV5, UV6); X7 = UV7 (resid + 2 lintel + 16 glass, depth);
// tint = vertex colour * 2. wpos / cam in UE cm, wn = UE world vertex normal. P = (InteriorGain, ShopGain, NightK, DnTime).
// Returns the albedo; outputs roughness, metallic, UE world-space normal, emissive, glass weight + F0 colour.
float3 CityFacade(TEXDECL, float2 fac, float4 F, float4 S, float4 W, float2 X7, float3 tint, float3 wposU, float3 wnU, float3 camU,
                  float4 P, float2 fragXY, out float rough, out float metal, out float3 nU, out float3 emis, out float glass, out float3 f0)
{
  vFac = fac; vF = F; vS = S; vW = W;
  float xp = floor(X7.x + 0.5);
  vX = float4(gmod(xp, 2.0), gmod(floor(xp / 2.0), 8.0), floor(xp / 16.0), X7.y);
  vTint = tint; vWPos = CityU2B(wposU) * 0.01; vWN = normalize(CityU2B(wnU)); gCamPos = CityU2B(camU) * 0.01; gFragCoord = fragXY;
  uInteriorGain = P.x; uShopGain = P.y; uNightK = P.z; uDnTime = P.w;
  Surf FS = facade(TEXPASS);
  float3 Nw = normalize(vWN);
  float3 Tw = Nw.y > 0.5 ? float3(1.0, 0.0, 0.0) : (Nw.y < -0.5 ? float3(1.0, 0.0, 0.0) : normalize(cross(float3(0.0, 1.0, 0.0), Nw)));
  float3 Bw = Nw.y > 0.5 ? float3(0.0, 0.0, -1.0) : (Nw.y < -0.5 ? float3(0.0, 0.0, 1.0) : float3(0.0, 1.0, 0.0));
  float3 nb = normalize(Tw * FS.n.x + Bw * FS.n.y + Nw * FS.n.z);
  nU = CityB2U(nb);
  rough = FS.rough; metal = FS.metal; emis = FS.emis;
  float cg = saturate(gGlass);
  // browser: specularColor -> gF0 * gSpecTint on glass, old sash glass dimmer (x (1 - 0.4 gSash)) and per-window gSashV
  f0 = gF0 * gSpecTint * (1.0 - 0.4 * gSash) * lerp(1.0, gSashV, gSash);
  glass = cg;
  return FS.alb;
}
`;
  fs.writeFileSync(path.join(OUT, 'Facade.ush'), ush);
  console.log('Facade.ush', ush.length);
}

// ------------------------------------------------------------------ detail (buildings.js createDetailMaterial)
{
  const js = src('buildings.js');
  const frag = between(between(js, 'export function createDetailMaterial', "mat.customProgramCacheKey"), "'#include <color_fragment>', `#include <color_fragment>", '`)');
  let g = frag.replace(/diffuseColor\.rgb/g, 'dC').replace(/\bdiscard\s*;/g, '{ gClip = 1.0; }');
  const TEX = [['tNoise', 0], ['tDetail', 0]];
  const { decl, pass } = texMacros(TEX);
  const body = translate(`void detailBody() ${g}`.replace('void detailBody()', 'float detailBody()').replace(/\}\s*$/, '  return 0.0; }'), { textures: TEX.map(t => t[0]) });
  const ush = `${HDR('buildings.js (createDetailMaterial)')}
#define TEXDECL ${decl}
#define TEXPASS ${pass}
${PRELUDE}${B2U}
static float vPart; static float3 vWP; static float3 vWN; static float2 vUv2; static float3 gCamPos; static float2 gFragCoord;
static float dR; static float dM; static float3 dN; static float3 dC; static float gClip = 0.0;
${body}
// UE entry: col = vertex colour (linear), part = UV1.x, uv = UV0. Returns albedo; rough / metal / UE-world normal / clip.
float3 CityDetail(TEXDECL, float3 col, float part, float2 uv, float3 wposU, float3 wnU, float3 camU, float2 fragXY,
                  out float rough, out float metal, out float3 nU, out float opacity)
{
  vPart = part; vWP = CityU2B(wposU) * 0.01; vWN = normalize(CityU2B(wnU)); vUv2 = uv; gCamPos = CityU2B(camU) * 0.01; gFragCoord = fragXY;
  dC = col; gClip = 0.0;
  detailBody(TEXPASS);
  float3 Nw = normalize(vWN); float3 Tw = abs(Nw.y) > 0.9 ? float3(1.0, 0.0, 0.0) : normalize(cross(float3(0.0, 1.0, 0.0), Nw)); float3 Bw = cross(Nw, Tw);
  float3 nb = normalize(Tw * dN.x + Bw * dN.y + Nw * dN.z);
  nU = CityB2U(nb); rough = dR; metal = dM; opacity = 1.0 - gClip;
  return dC;
}
`;
  fs.writeFileSync(path.join(OUT, 'Detail.ush'), ush);
  console.log('Detail.ush', ush.length);
}

// ------------------------------------------------------------------ roofs (rooftops.js createRoofMaterial)
{
  const js = src('rooftops.js');
  const fn = between(js, 'function createRoofMaterial', 'mat.customProgramCacheKey');
  // the JS template interpolates the constant tables: evaluate them from the module source
  const consts = {};
  for (const k of ['CELL_ROUGH', 'PONDS', 'SEAM', 'TARP']) consts[k] = JSON.parse(between(js, `const ${k} = `, ';').replace(/\/\/.*$/gm, ''));
  const CELL = Function('return ' + between(js, 'export const CELL = ', ';'))();
  const interp = (t) => t.replace(/\$\{([^}]*)\}/g, (_, e) => {
    const f = Function('CELL_ROUGH', 'PONDS', 'SEAM', 'TARP', 'CELL', 'return (' + e + ');');
    return String(f(consts.CELL_ROUGH, consts.PONDS, consts.SEAM, consts.TARP, CELL));
  });
  const decls = interp(between(fn, "'#include <common>', `#include <common>\n      uniform highp sampler2DArray tRoofC;", '`)'));
  const frag = interp(between(fn, "'#include <color_fragment>', `#include <color_fragment>", '`)'));
  const TEX = [['tRoofC', 1], ['tRoofN', 1], ['tNoiseR', 0]];
  const { decl, pass } = texMacros(TEX);
  const g = frag.replace(/diffuseColor\.rgb/g, 'dC');
  const body = translate(decls.replace(/^[^\n]*\n/, '') + '\nfloat roofBody() ' + g.replace(/\}\s*$/, '  return 0.0; }'), { arrays: new Set(['tRoofC', 'tRoofN']), textures: TEX.map(t => t[0]) });
  const ush = `${HDR('rooftops.js (createRoofMaterial)')}
#define TEXDECL ${decl}
#define TEXPASS ${pass}
${PRELUDE}${B2U}
static float2 vRUv; static float4 vM; static float4 vE; static float3 vRWP; static float3 vRWN; static float3 gCamPos; static float3 dC;
${body}
// UE entry: col = vertex colour, uv = UV0, M = (UV1, UV2), E = (UV3, UV4)
float3 CityRoof(TEXDECL, float3 col, float2 uv, float4 M, float4 E, float3 wposU, float3 wnU, float3 camU, out float rough, out float metal, out float3 nU)
{
  vRUv = uv; vM = M; vE = E; vRWP = CityU2B(wposU) * 0.01; vRWN = normalize(CityU2B(wnU)); gCamPos = CityU2B(camU) * 0.01; dC = col;
  roofBody(TEXPASS);
  float3 Nw = normalize(vRWN); float3 Tw, Bw;
  if (abs(Nw.y) > 0.5) { Tw = float3(1.0, 0.0, 0.0); Bw = float3(0.0, 0.0, -1.0); } else { Tw = normalize(cross(float3(0.0, 1.0, 0.0), Nw)); Bw = float3(0.0, 1.0, 0.0); }
  float3 nb = normalize(Tw * rN.x + Bw * rN.y + Nw * rN.z);
  nU = CityB2U(nb); rough = rR; metal = rM;
  return dC;
}
`;
  fs.writeFileSync(path.join(OUT, 'Roof.ush'), ush);
  console.log('Roof.ush', ush.length);
}

// ------------------------------------------------------------------ asphalt + sidewalk (ground.js)
for (const [name, marker, fnName, TEX, entry] of [
  ['Asphalt', 'export function createAsphaltMaterial', 'asphalt', [['tCol', 0], ['tNrm', 0], ['tMacro', 0], ['tNoise', 0], ['tDec', 0]], `
// UE entry: road = (UV0.x, UV0.y, UV1.x) = aRoad
float3 CityAsphalt(TEXDECL, float3 road, float3 wposU, float3 camU, out float rough, out float3 nU)
{
  vWP = CityU2B(wposU) * 0.01; vRoad = road; gCamPos = CityU2B(camU) * 0.01;
  float3 c = asphalt(TEXPASS);
  float3 nb = normalize(float3(aN.x, aN.z, aN.y));
  nU = CityB2U(nb); rough = aR;
  return c;
}`],
  ['Sidewalk', 'export function createSidewalkMaterial', 'walk', [['tCol', 0], ['tNrm', 0], ['tNoise', 0], ['tCurb', 0]], `
// UE entry: rect = (UV0, UV1) = aRect
float3 CitySidewalk(TEXDECL, float4 rect, float3 wposU, float3 wnU, float3 camU, out float rough, out float3 nU)
{
  vRect = rect; vWP = CityU2B(wposU) * 0.01; vWN = normalize(CityU2B(wnU)); gCamPos = CityU2B(camU) * 0.01;
  float3 c = walk(TEXPASS);
  float3 nb = vWN.y > 0.5 ? normalize(float3(sN.x, sN.z, sN.y)) : vWN;
  nU = CityB2U(nb); rough = sR;
  return c;
}`]]) {
  const js = src('ground.js');
  const fn = between(js, marker, 'mat.customProgramCacheKey');
  const decls = between(fn, "'#include <common>', `#include <common>", '`)');
  const { decl, pass } = texMacros(TEX);
  const body = translate(decls, { textures: TEX.map(t => t[0]) });
  const ush = `${HDR('ground.js (' + marker.split(' ').pop() + ')')}
#define TEXDECL ${decl}
#define TEXPASS ${pass}
${PRELUDE}${B2U}
static float3 vWP; static float3 vRoad; static float4 vRect; static float3 vWN; static float3 gCamPos;
${body}
${entry}
`;
  fs.writeFileSync(path.join(OUT, name + '.ush'), ush);
  console.log(name + '.ush', ush.length, fnName);
}
