JOB_ARGS = {"steps": "mat"}
# Homage fan game. Not an official Marvel, Sony or Insomniac game; no affiliation.
# P1 City: idempotent rebuild of /Game/City and /Game/Tests/City from committed sources.
#   sources: browser city export (tools/export/export_city.mjs -> <EXPORT>/manifest.json, mesh/, proto/, layout.json)
#            textures prepared by tools/export/prep_textures.py (<TEX>), shader includes Shaders/City/*.ush
#            (generated by tools/export/gen_shaders.mjs from src/world/*.js)
#   run: tools/export/build_city.sh (export + prep + this script in the P1 editor or headless -run=pythonscript)
# Frame: browser metres (x east, y up, z south) -> UE cm: X = 100 x, Y = 100 z, Z = 100 y (north = -Y).
import unreal, os, json, math, time

EXPORT = os.environ.get('SM2_CITY_EXPORT', '/Users/midir/sm2-n1/_scratch/city/export/midtown3x3')
TEX = os.environ.get('SM2_CITY_TEX', '/Users/midir/sm2-n1/_scratch/city/tex')
try: ARGS = JOB_ARGS  # noqa: F821 (set by tools/export/ue/uejob.py)
except NameError: ARGS = {}
STEPS = set((ARGS.get('steps') or 'clean,tex,mat,mesh,proto,map').split(','))
ROOT, TESTS = '/Game/City', '/Game/Tests/City'
at = unreal.AssetToolsHelpers.get_asset_tools()
EAL = unreal.EditorAssetLibrary
mel = unreal.MaterialEditingLibrary
T0 = time.time()
def log(*a): print('[build_city %5.0fs]' % (time.time() - T0), *a)

# ------------------------------------------------------------------------------------------------ helpers
def import_files(files, dest, pipeline=None):
    tasks = []
    for f in files:
        t = unreal.AssetImportTask(); t.filename = f; t.destination_path = dest; t.automated = True; t.replace_existing = True; t.save = False
        if pipeline: t.options = pipeline
        tasks.append(t)
    at.import_asset_tasks(tasks)
    return tasks

def tex_settings(t, srgb, comp=unreal.TextureCompressionSettings.TC_BC7, wrap=True):
    t.set_editor_property('srgb', srgb)
    t.set_editor_property('compression_settings', comp)
    if not wrap:
        t.set_editor_property('address_x', unreal.TextureAddress.TA_CLAMP); t.set_editor_property('address_y', unreal.TextureAddress.TA_CLAMP)

def load(p): return unreal.load_asset(p)

# ------------------------------------------------------------------------------------------------ clean
if 'clean' in STEPS:
    unreal.EditorLoadingAndSavingUtils.new_blank_map(False)
    for d in (ROOT,):  # test maps are reused / emptied by the map step (deleting maps pops a modal dialog)
        if EAL.does_directory_exist(d): EAL.delete_directory(d)
    log('cleaned')

# ------------------------------------------------------------------------------------------------ textures
PLAIN_SRGB = {'interiors': True, 'signs': True, 'noise': False, 'detail_nrm': False, 'asphalt_col': True, 'asphalt_nrm': False, 'asphalt_macro': False,
              'asphalt_decals': False, 'sidewalk_col': True, 'sidewalk_nrm': False, 'curb_col': True, 'markings': True, 'leaves': True, 'water_nrm': False}
ARRAYS = {'walls_col': (16, True), 'walls_nrm': (16, False), 'walls_hao': (17, False), 'roof_col': (19, True), 'roof_nrm': (19, False)}
if 'tex' in STEPS:
    import_files([os.path.join(TEX, k + '.png') for k in PLAIN_SRGB], ROOT + '/Textures')
    for k, s in PLAIN_SRGB.items():
        t = load(f'{ROOT}/Textures/{k}')
        tex_settings(t, s, unreal.TextureCompressionSettings.TC_VECTOR_DISPLACEMENTMAP if k == 'noise' else unreal.TextureCompressionSettings.TC_BC7,
                     wrap=k not in ('interiors', 'signs', 'markings', 'leaves'))

    maps = sorted(f for f in os.listdir(os.path.join(TEX, 'maps')) if f.endswith('.png'))
    import_files([os.path.join(TEX, 'maps', f) for f in maps], ROOT + '/Textures/Maps')
    for f in maps:
        t = load(f'{ROOT}/Textures/Maps/{f[:-4]}'); tex_settings(t, 'noise' not in f)
    for name, (n, srgb) in ARRAYS.items():
        files = [os.path.join(TEX, f'{name}_L{k:02d}.png') for k in range(n)]
        import_files(files, ROOT + '/Textures/Layers')
        layers = []
        for k in range(n):
            t = load(f'{ROOT}/Textures/Layers/{name}_L{k:02d}'); tex_settings(t, srgb); layers.append(t)
        arr = load(f'{ROOT}/Textures/TA_{name}') if EAL.does_asset_exist(f'{ROOT}/Textures/TA_{name}') else at.create_asset('TA_' + name, ROOT + '/Textures', unreal.Texture2DArray, unreal.Texture2DArrayFactory())
        arr.set_editor_property('source_textures', layers)  # PostEditChange rebuilds the array source from the layers
        tex_settings(arr, srgb)
        arr.set_editor_property('address_x', unreal.TextureAddress.TA_WRAP); arr.set_editor_property('address_y', unreal.TextureAddress.TA_WRAP)
    EAL.save_directory(ROOT + '/Textures', only_if_is_dirty=False, recursive=True)
    log('textures done')

# ------------------------------------------------------------------------------------------------ materials
MAT = ROOT + '/Materials'
def sampler_for(t):
    if isinstance(t, unreal.Texture2DArray) or True:
        return unreal.MaterialSamplerType.SAMPLERTYPE_COLOR if t.get_editor_property('srgb') else unreal.MaterialSamplerType.SAMPLERTYPE_LINEAR_COLOR

def make_material(name, include, code, inputs, outputs, blend='opaque', two_sided=False, world_normal=True, domain_hint=None, scalar_defaults=None, shading=None):
    """inputs: list of (name, kind, arg): kind in tex|uv|vc|wpos|wn|cam|scalar|mpc|pcd.  outputs: list of (name, n, property)."""
    path = f'{MAT}/{name}'
    if EAL.does_asset_exist(path):  # reuse (deleting a referenced material pops a dialog): clear its graph
        m = load(path); mel.delete_all_material_expressions(m)
    else:
        m = at.create_asset(name, MAT, unreal.Material, unreal.MaterialFactoryNew())
    m.set_editor_property('tangent_space_normal', not world_normal)
    if blend == 'masked': m.set_editor_property('blend_mode', unreal.BlendMode.BLEND_MASKED)
    m.set_editor_property('two_sided', two_sided)
    if shading: m.set_editor_property('shading_model', shading)
    c = mel.create_material_expression(m, unreal.MaterialExpressionCustom, -400, 0)
    c.set_editor_property('code', code)
    c.set_editor_property('output_type', unreal.CustomMaterialOutputType.CMOT_FLOAT3)
    c.set_editor_property('description', name)
    if include: c.set_editor_property('include_file_paths', [include])
    ins = []
    for n, kind, arg in inputs:
        ci = unreal.CustomInput(); ci.set_editor_property('input_name', n); ins.append(ci)
    c.set_editor_property('inputs', ins)
    outs = []
    for n, k, _ in outputs[1:]:
        co = unreal.CustomOutput(); co.set_editor_property('output_name', n)
        co.set_editor_property('output_type', [None, unreal.CustomMaterialOutputType.CMOT_FLOAT1, unreal.CustomMaterialOutputType.CMOT_FLOAT2, unreal.CustomMaterialOutputType.CMOT_FLOAT3][k])
        outs.append(co)
    c.set_editor_property('additional_outputs', outs)
    y = -1200
    for n, kind, arg in inputs:
        y += 90
        if kind == 'tex':
            e = mel.create_material_expression(m, unreal.MaterialExpressionTextureObject, -900, y)
            t = load(arg); e.set_editor_property('texture', t); e.set_editor_property('sampler_type', sampler_for(t))
        elif kind == 'texparam':
            e = mel.create_material_expression(m, unreal.MaterialExpressionTextureObjectParameter, -900, y)
            e.set_editor_property('parameter_name', n); t = load(arg); e.set_editor_property('texture', t); e.set_editor_property('sampler_type', sampler_for(t))
        elif kind == 'uv':
            e = mel.create_material_expression(m, unreal.MaterialExpressionTextureCoordinate, -900, y); e.set_editor_property('coordinate_index', arg)
        elif kind == 'vc':
            e = mel.create_material_expression(m, unreal.MaterialExpressionVertexColor, -900, y)
        elif kind == 'wpos':
            e = mel.create_material_expression(m, unreal.MaterialExpressionWorldPosition, -900, y)
        elif kind == 'wn':
            e = mel.create_material_expression(m, unreal.MaterialExpressionVertexNormalWS, -900, y)
        elif kind == 'cam':
            e = mel.create_material_expression(m, unreal.MaterialExpressionCameraPositionWS, -900, y)
        elif kind == 'scalar':
            e = mel.create_material_expression(m, unreal.MaterialExpressionScalarParameter, -900, y)
            e.set_editor_property('parameter_name', n); e.set_editor_property('default_value', arg)
        elif kind == 'vector':
            e = mel.create_material_expression(m, unreal.MaterialExpressionVectorParameter, -900, y)
            e.set_editor_property('parameter_name', n); e.set_editor_property('default_value', unreal.LinearColor(*arg))
        elif kind == 'mpc':
            e = mel.create_material_expression(m, unreal.MaterialExpressionCollectionParameter, -900, y)
            e.set_editor_property('collection', load(MAT + '/MPC_City')); e.set_editor_property('parameter_name', arg)
        elif kind == 'time':
            e = mel.create_material_expression(m, unreal.MaterialExpressionTime, -900, y)
        elif kind == 'pcd':
            e = mel.create_material_expression(m, unreal.MaterialExpressionPerInstanceCustomData, -900, y)
            e.set_editor_property('data_index', arg[0])
        mel.connect_material_expressions(e, '', c, n)
    for i, (n, k, prop) in enumerate(outputs):
        if prop is None: continue
        mel.connect_material_property(c, '' if i == 0 else n, prop)
    # usage flags must be saved: in -game an instanced / Nanite mesh whose material lacks the flag renders the default material
    for u in (unreal.MaterialUsage.MATUSAGE_NANITE, unreal.MaterialUsage.MATUSAGE_INSTANCED_STATIC_MESHES):
        mel.set_material_usage(m, u)
    mel.recompile_material(m)
    EAL.save_asset(path)
    return m

MP = unreal.MaterialProperty
TEXA = lambda n: f'{ROOT}/Textures/{n}'
WORLD = [('wpos', 'wpos', None), ('wn', 'wn', None), ('cam', 'cam', None)]

# (r04) MPC_City scalars. DayEmisK scales the facade's interior / sign emission in daylight (1.0 at night): rooms behind
# window glass are ~10x darker than sunlit masonry; GlassSpec = UE Specular of dielectric sash glass (0.5 = F0 0.04, real
# glass; r03 used 0.1375 = F0 0.011, which turned every masonry window into a flat unreflective slab); DebugMode 1 = facade
# emissive only, 2 = facade without emissive (visual debugging without recompiling the material).
MPC_DEFAULTS = (('NightK', 0.0), ('DnTime', 0.0), ('InteriorGain', 0.5), ('ShopGain', 0.7), ('EmissiveScale', 3.0),
                ('DayEmisK', 0.3), ('GlassSpec', 0.5), ('DebugMode', 0.0))
if 'mat' in STEPS:
    # the editor caches shader source files: reload the regenerated /Project/City/*.ush includes
    unreal.SystemLibrary.execute_console_command(None, 'recompileshaders changed')
    if not EAL.does_asset_exist(MAT + '/MPC_City'):
        mpc = at.create_asset('MPC_City', MAT, unreal.MaterialParameterCollection, unreal.MaterialParameterCollectionFactoryNew())
        sp = []
        for n, v in MPC_DEFAULTS:
            p = unreal.CollectionScalarParameter(); p.set_editor_property('parameter_name', n); p.set_editor_property('default_value', v); sp.append(p)
        mpc.set_editor_property('scalar_parameters', sp); EAL.save_asset(MAT + '/MPC_City')
    else:  # (r04) existing collection: add the parameters introduced later, keep tuned values of the old ones
        mpc = load(MAT + '/MPC_City'); sp = list(mpc.get_editor_property('scalar_parameters')); have = {str(q.get_editor_property('parameter_name')) for q in sp}
        for n, v in MPC_DEFAULTS:
            if n in have: continue
            p = unreal.CollectionScalarParameter(); p.set_editor_property('parameter_name', n); p.set_editor_property('default_value', v); sp.append(p)
        mpc.set_editor_property('scalar_parameters', sp); EAL.save_asset(MAT + '/MPC_City')
    # facade (facade.js FRAG_DECL port)
    make_material('M_CityFacade', '/Project/City/Facade.ush', '''
float r, m, g; float3 n, e, f;
float3 a = CityFacade(tWallC, tWallCSampler, tWallN, tWallNSampler, tWallH, tWallHSampler, tDetail, tDetailSampler, tInterior, tInteriorSampler, tSigns, tSignsSampler, tNoise, tNoiseSampler,
  uv0, float4(uv1, uv2), float4(uv3, uv4), float4(uv5, uv6), uv7, vc.rgb * 2.0, wpos, wn, cam, float4(igain, sgain, nightk, dntime), float2(0.0, 0.0), r, m, n, e, g, f);
// coated curtain glass (F0 0.2-0.6): metallic mirror = F0 x tint. Old sash glass (gSash): dielectric with F0 = 0.011 so
// that UE's F90 = saturate(50 F0) = 0.55 matches the browser's specularF90 0.55 (no bright grazing mirrors on masonry)
float gm = g * (1.0 - gSash);
float ek = lerp(dayemis, 1.0, saturate(nightk));
float3 col = lerp(a, f, gm); float3 em = e * escale * ek;
if (dbgmode > 0.5 && dbgmode < 1.5) col = float3(0, 0, 0);
if (dbgmode > 1.5 && dbgmode < 2.5) em = float3(0, 0, 0);
if (dbgmode > 2.5 && dbgmode < 3.5) { col = float3(0, 0, 0); em = float3(saturate(g) * 0.05, 0, 0); }  // window (glass) mask for the brightness test
if (dbgmode > 4.5 && dbgmode < 5.5) { col = float3(0, 0, 0); em = 0.3 * Texture2DSampleLevel(tInterior, tInteriorSampler, frac(uv0 * 0.05), 0.0).rgb; }
if (dbgmode > 5.5 && dbgmode < 6.5) { col = float3(0, 0, 0); em = 0.3 * interior(TEXPASS, frac(uv0 * 0.3) * 3.0, normalize(float3(0.2, 0.1, -1.0)), 3.0, 3.0, 4.0, 6.0, 1.0, 0.0); }
if (dbgmode > 6.5 && dbgmode < 7.5) { col = float3(0, 0, 0); em = 0.3 * Texture2DSampleLevel(tInterior, tInteriorSampler, frac(uv0 * 0.05), gLodI).rgb; }
if (dbgmode > 7.5 && dbgmode < 8.5) { col = float3(0, 0, 0); em = 0.05 * float3(gLodI > 2.0, gLodI > 4.0, gLodI > 6.0); }
if (dbgmode > 8.5 && dbgmode < 9.5) { col = float3(0, 0, 0); em = 0.05 * float3(gLodI > 7.0, gLodI > 8.0, gLodI > 8.9); }
if (dbgmode > 9.5 && dbgmode < 10.5) { col = float3(0, 0, 0); em = 0.3 * Texture2DSampleLevel(tSigns, tSignsSampler, frac(uv0 * 0.02), 0.0).rgb; }
if (dbgmode > 3.5 && dbgmode < 4.5) { col = float3(0, 0, 0); em = 0.05 * float3(gLodI / 9.0, saturate(length(gDx) * 100.0), saturate(vF.y / 16.0)); }
Rough = (dbgmode > 2.5 && dbgmode < 3.5) ? 1.0 : r; Metal = lerp(m, 1.0, gm); NormalW = n; Emis = em; Spec = (dbgmode > 2.5 && dbgmode < 3.5) ? 0.0 : lerp(0.5, glassspec, g * gSash);
return col;''',
        [('tWallC', 'tex', TEXA('TA_walls_col')), ('tWallN', 'tex', TEXA('TA_walls_nrm')), ('tWallH', 'tex', TEXA('TA_walls_hao')), ('tDetail', 'tex', TEXA('detail_nrm')),
         ('tInterior', 'tex', TEXA('interiors')), ('tSigns', 'tex', TEXA('signs')), ('tNoise', 'tex', TEXA('noise'))]
        + [(f'uv{i}', 'uv', i) for i in range(8)] + [('vc', 'vc', None)] + WORLD
        + [('igain', 'mpc', 'InteriorGain'), ('sgain', 'mpc', 'ShopGain'), ('nightk', 'mpc', 'NightK'), ('dntime', 'mpc', 'DnTime'), ('escale', 'mpc', 'EmissiveScale'),
           ('dayemis', 'mpc', 'DayEmisK'), ('glassspec', 'mpc', 'GlassSpec'), ('dbgmode', 'mpc', 'DebugMode')],
        [('', 3, MP.MP_BASE_COLOR), ('Rough', 1, MP.MP_ROUGHNESS), ('Metal', 1, MP.MP_METALLIC), ('NormalW', 3, MP.MP_NORMAL), ('Emis', 3, MP.MP_EMISSIVE_COLOR), ('Spec', 1, MP.MP_SPECULAR)])
    make_material('M_CityDetail', '/Project/City/Detail.ush', '''
float r, m, o; float3 n;
float3 a = CityDetail(tNoise, tNoiseSampler, tDetail, tDetailSampler, vc.rgb, uv1.x, uv0, wpos, wn, cam, Parameters.SvPosition.xy, r, m, n, o);
Rough = r; Metal = m; NormalW = n; Op = o; return a;''',
        [('tNoise', 'tex', TEXA('noise')), ('tDetail', 'tex', TEXA('detail_nrm')), ('uv0', 'uv', 0), ('uv1', 'uv', 1), ('vc', 'vc', None)] + WORLD,
        [('', 3, MP.MP_BASE_COLOR), ('Rough', 1, MP.MP_ROUGHNESS), ('Metal', 1, MP.MP_METALLIC), ('NormalW', 3, MP.MP_NORMAL), ('Op', 1, MP.MP_OPACITY_MASK)], blend='masked')
    make_material('M_CityRoof', '/Project/City/Roof.ush', '''
float r, m; float3 n;
float3 a = CityRoof(tRoofC, tRoofCSampler, tRoofN, tRoofNSampler, tNoiseR, tNoiseRSampler, vc.rgb, uv0, float4(uv1, uv2), float4(uv3, uv4), wpos, wn, cam, r, m, n);
Rough = r; Metal = m; NormalW = n; return a;''',
        [('tRoofC', 'tex', TEXA('TA_roof_col')), ('tRoofN', 'tex', TEXA('TA_roof_nrm')), ('tNoiseR', 'tex', TEXA('noise'))] + [(f'uv{i}', 'uv', i) for i in range(5)] + [('vc', 'vc', None)] + WORLD,
        [('', 3, MP.MP_BASE_COLOR), ('Rough', 1, MP.MP_ROUGHNESS), ('Metal', 1, MP.MP_METALLIC), ('NormalW', 3, MP.MP_NORMAL)])
    make_material('M_CityAsphalt', '/Project/City/Asphalt.ush', '''
float r; float3 n;
float3 a = CityAsphalt(tCol, tColSampler, tNrm, tNrmSampler, tMacro, tMacroSampler, tNoise, tNoiseSampler, tDec, tDecSampler, float3(uv0, uv1.x), wpos, cam, r, n);
Rough = r; NormalW = n; return a;''',
        [('tCol', 'tex', TEXA('asphalt_col')), ('tNrm', 'tex', TEXA('asphalt_nrm')), ('tMacro', 'tex', TEXA('asphalt_macro')), ('tNoise', 'tex', TEXA('noise')), ('tDec', 'tex', TEXA('asphalt_decals')),
         ('uv0', 'uv', 0), ('uv1', 'uv', 1), ('wpos', 'wpos', None), ('cam', 'cam', None)],
        [('', 3, MP.MP_BASE_COLOR), ('Rough', 1, MP.MP_ROUGHNESS), ('NormalW', 3, MP.MP_NORMAL)])
    make_material('M_CitySidewalk', '/Project/City/Sidewalk.ush', '''
float r; float3 n;
float3 a = CitySidewalk(tCol, tColSampler, tNrm, tNrmSampler, tNoise, tNoiseSampler, tCurb, tCurbSampler, float4(uv0, uv1), wpos, wn, cam, r, n);
Rough = r; NormalW = n; return a;''',
        [('tCol', 'tex', TEXA('sidewalk_col')), ('tNrm', 'tex', TEXA('sidewalk_nrm')), ('tNoise', 'tex', TEXA('noise')), ('tCurb', 'tex', TEXA('curb_col')), ('uv0', 'uv', 0), ('uv1', 'uv', 1)] + WORLD,
        [('', 3, MP.MP_BASE_COLOR), ('Rough', 1, MP.MP_ROUGHNESS), ('NormalW', 3, MP.MP_NORMAL)])
    # generic vertex-colour / atlas material (Times Square dressing, signage, markings): masked by the map alpha
    make_material('M_CityVC', None, '''
float4 t = UseMap > 0.5 ? Texture2DSample(Map, MapSampler, float2(uv0.x, 1.0 - uv0.y)) : float4(1, 1, 1, 1);
float3 c = vc.rgb * Tint.rgb * t.rgb;
Rough = RoughP; Metal = MetalP; Op = t.a > AlphaCut ? 1.0 : 0.0; Emis = c * EmisGain;
return c;''',
        [('Map', 'texparam', TEXA('markings')), ('UseMap', 'scalar', 0.0), ('uv0', 'uv', 0), ('vc', 'vc', None), ('Tint', 'vector', (1, 1, 1, 1)),
         ('RoughP', 'scalar', 0.7), ('MetalP', 'scalar', 0.0), ('EmisGain', 'scalar', 0.0), ('AlphaCut', 'scalar', 0.0)],
        [('', 3, MP.MP_BASE_COLOR), ('Rough', 1, MP.MP_ROUGHNESS), ('Metal', 1, MP.MP_METALLIC), ('Op', 1, MP.MP_OPACITY_MASK), ('Emis', 3, MP.MP_EMISSIVE_COLOR)],
        blend='masked', world_normal=False)
    # props (partmat.js port): per-part roughness / metal / emission, per-instance tint in custom data 0..2, state in 3
    make_material('M_CityProp', None, '''
float4 t = UseMap > 0.5 ? Texture2DSample(Map, MapSampler, float2(uv0.x, 1.0 - uv0.y)) : float4(1, 1, 1, 1);
float3 c = vc.rgb * t.rgb; int P = (int)(uv1.x + 0.5); float3 tint = (t0 + t1 + t2) > 0.0 ? float3(t0, t1, t2) : float3(1, 1, 1); float st = t3;
float pR = 0.7, pM = 0.0; float3 pE = 0;
if (P == 1) { c *= tint; pR = 0.32; } else if (P == 2) { pR = 0.28; pM = 1.0; } else if (P == 3) { c = float3(0.012, 0.014, 0.016); pR = 0.04; }
else if (P == 4) { pR = 0.2; pE = c * 0.4; } else if (P == 5) pR = 0.92; else if (P == 6) pR = 0.55; else if (P == 7) { pR = 0.08; pM = 0.6; pE = 0.12; }
else if (P == 8) { pR = 0.2; pE = c * (0.3 + st * 7.0); } else if (P == 9) pR = 0.85;
else if (P >= 10 && P <= 12) { float on = abs(float(P - 10) - st) < 0.5 ? 1.0 : 0.0; float3 lc = P == 10 ? float3(1, 0.06, 0.03) : (P == 11 ? float3(1, 0.5, 0.02) : float3(0.05, 1, 0.45)); c = lc * 0.05; pR = 0.15; pE = lc * on * 30.0; }
else if (P == 13) { float3 lc = st > 1.5 ? float3(0.9, 0.95, 1.0) : float3(1.0, 0.45, 0.05); c = lc * 0.05; pE = lc * 10.0; }
else if (P == 14) { pR = 0.1; pE = c * 3.0; } else if (P == 15) { pR = 0.3; pE = c * 0.25; } else if (P >= 16 && P <= 22) pR = 0.8;
if (nightk > 0.0) { if (P == 4) pE += float3(1.0, 0.78, 0.5) * 9.0 * nightk; else if (P == 7) pE += float3(1.0, 0.93, 0.8) * 7.0 * nightk; }
Rough = pR; Metal = pM; Emis = pE * escale;
return c;''',
        [('Map', 'texparam', TEXA('markings')), ('UseMap', 'scalar', 0.0), ('uv0', 'uv', 0), ('uv1', 'uv', 1), ('vc', 'vc', None),
         ('t0', 'pcd', (0, 1.0)), ('t1', 'pcd', (1, 1.0)), ('t2', 'pcd', (2, 1.0)), ('t3', 'pcd', (3, 0.0)), ('nightk', 'mpc', 'NightK'), ('escale', 'mpc', 'EmissiveScale')],
        [('', 3, MP.MP_BASE_COLOR), ('Rough', 1, MP.MP_ROUGHNESS), ('Metal', 1, MP.MP_METALLIC), ('Emis', 3, MP.MP_EMISSIVE_COLOR)], world_normal=False)
    # tree leaves: alpha-tested cards, two-sided, per-vertex / per-instance tint
    # (r03) ez-tree leaf cards (eztrees.js): leaf-shaped alpha, green albedo from the leaf texture, per-leaf crown exposure
    # (aLeafE.x in UV1: 0 deep inside .. 1 outer sun-side shell), two-sided foliage shading: light passes through the leaves
    make_material('M_CityLeaves', None, '''
float4 t = Texture2DSample(Map, MapSampler, float2(uv0.x, 1.0 - uv0.y));
float e = saturate(uv1.x);
float3 c = min(t.rgb * Tint.rgb * lerp(2.1, 3.0, e), 0.6);
Op = t.a > 0.5 ? 1.0 : 0.0; Sub = saturate(c * float3(1.1, 1.3, 0.6) * 1.2); Rough = 0.7;
return c;''',
        [('Map', 'texparam', TEXA('leaves')), ('uv0', 'uv', 0), ('uv1', 'uv', 1), ('Tint', 'vector', (1, 1, 1, 1))],
        [('', 3, MP.MP_BASE_COLOR), ('Op', 1, MP.MP_OPACITY_MASK), ('Sub', 3, MP.MP_SUBSURFACE_COLOR), ('Rough', 1, MP.MP_ROUGHNESS)],
        blend='masked', two_sided=True, world_normal=False, shading=unreal.MaterialShadingModel.MSM_TWO_SIDED_FOLIAGE)
    # (r04) Times Square frame / housing blocks (tsFrames): the exporter paints the big billboard housings vertex-colour black (0.018),
    # which rendered as untextured black masses (critic r03: S5 top right). Dark gunmetal cladding: 1.5 x 3 m panel seams, per-panel
    # tone, grime, metallic sheen; lighter frame parts (gold, chrome, white trim) keep their vertex colour.
    make_material('M_CityFrame', None, r"""
float3 p = wpos * 0.01; float3 an = abs(normalize(wn));
float2 q = an.x > max(an.y, an.z) ? p.yz : (an.y > an.z ? p.xz : p.xy);
float3 nz = Texture2DSampleLevel(tNoise, tNoiseSampler, q / 6.0, 0.0).rgb;
float3 nz2 = Texture2DSampleLevel(tNoise, tNoiseSampler, q / 1.3, 0.0).rgb;
float2 pn = floor(q / float2(1.5, 3.0));
float pv = frac(sin(dot(pn, float2(12.9898, 78.233))) * 43758.5453);
float2 g = frac(q / float2(1.5, 3.0));
float seam = 1.0 - smoothstep(0.0, 0.035, min(min(g.x, 1.0 - g.x) * 1.5, min(g.y, 1.0 - g.y) * 3.0));
float lv = dot(vc.rgb, float3(0.2126, 0.7152, 0.0722));
float dark = 1.0 - smoothstep(0.03, 0.08, lv);
float3 steel = float3(0.075, 0.08, 0.092) * (0.7 + 0.35 * pv + 0.3 * nz.g) * (1.0 - 0.5 * seam) * (1.0 - 0.3 * smoothstep(0.55, 0.85, nz2.r));
Rough = lerp(0.5, 0.42 + 0.3 * nz2.g, dark); Metal = lerp(0.5, 0.65, dark);
return lerp(vc.rgb, steel, dark);""",
        [('tNoise', 'tex', TEXA('noise')), ('vc', 'vc', None), ('wpos', 'wpos', None), ('wn', 'wn', None)],
        [('', 3, MP.MP_BASE_COLOR), ('Rough', 1, MP.MP_ROUGHNESS), ('Metal', 1, MP.MP_METALLIC)], world_normal=False)
    # (r04) signage.js port (signMaterial): vSig = UV1 (kind, gain), vLoc = UV2, vMapUv = UV0 (u 0..1 ads atlas, +2 ts_signs, +4 city_signart).
    # Kinds: 0 metal, 1 printed vinyl, 2 painted on brick, 3 LED screen, 4 back-lit box, 6 marquee bulbs, 7 fabric, 8 / 9 letters, else ghost sign.
    make_material('M_CitySignage', None, r"""
float2 vMapUv = uv0; float2 vSig = uv1; float2 vLoc = uv2;
float3 vWPs = float3(wpos.x, wpos.z, wpos.y) * 0.01;
float2 dx = ddx(vMapUv), dy = ddy(vMapUv);
int K = (int)(vSig.x + 0.5);
float2 lp = vMapUv * 1024.0; float2 ledF = frac(lp) - 0.5;
float ledAA = saturate(1.6 - 2.2 * max(abs(ddx(lp.x)) + abs(ddy(lp.x)), abs(ddx(lp.y)) + abs(ddy(lp.y))));
float2 uvA = vMapUv; float2 uvS = vMapUv - float2(2.0, 0.0); float2 uvR = vMapUv - float2(4.0, 0.0);
float2 uvL = lerp(vMapUv, (floor(lp) + 0.5) / 1024.0, ledAA);
float4 tA = Texture2DSampleGrad(tAds, tAdsSampler, float2(uvA.x, 1.0 - uvA.y), dx, dy);
float4 tS = Texture2DSampleGrad(tSigns, tSignsSampler, float2(saturate(uvS.x), 1.0 - uvS.y), dx, dy);
float4 tR = Texture2DSampleGrad(tArt, tArtSampler, float2(saturate(uvR.x), 1.0 - uvR.y), dx, dy);
float4 tLed = Texture2DSampleGrad(tAds, tAdsSampler, float2(uvL.x, 1.0 - uvL.y), dx, dy);
float4 bS = Texture2DSampleLevel(tSigns, tSignsSampler, float2(saturate(uvS.x), 1.0 - uvS.y), 5.0);
float4 bR = Texture2DSampleLevel(tArt, tArtSampler, float2(saturate(uvR.x), 1.0 - uvR.y), 5.0);
float3 nzA = Texture2DSampleLevel(tNoise, tNoiseSampler, (vWPs.xz + vWPs.yy * float2(0.7, -0.4)) / 9.0, 0.0).rgb;
float3 nzB = Texture2DSampleLevel(tNoise, tNoiseSampler, (vWPs.xz * 0.6 + vWPs.yy * float2(-0.5, 0.8)) / 1.7, 0.0).rgb;
float4 tx = float4(1, 1, 1, 1);
if (K == 3) tx = tLed; else if (K > 0 && K != 6 && K != 7) tx = vMapUv.x > 3.5 ? tR : (vMapUv.x > 1.5 ? tS : tA);
float lum = dot(tx.rgb, float3(0.2126, 0.7152, 0.0722));
float3 dc = vc.rgb; float sgR = 0.55; float sgM = 0.0; float3 sgE = float3(0, 0, 0); float opv = 1.0;
if (K == 0) { sgR = 0.5 + 0.3 * nzB.r; sgM = 0.35; dc *= 0.85 + 0.3 * nzA.g; }
else if (K == 1) {
  tx.rgb = lerp(tx.rgb, float3(lum, lum, lum), 0.32) * 0.86 + 0.02;
  tx.rgb = lerp(tx.rgb, float3(1, 1, 1) * (lum * 0.85 + 0.1), smoothstep(0.35, 0.8, nzA.b) * 0.16 + 0.08 * vLoc.y);
  float stk = smoothstep(0.55, 0.9, Texture2DSampleLevel(tNoise, tNoiseSampler, float2(vWPs.x + vWPs.z, vWPs.y * 0.08) * 0.35, 0.0).g) * (0.35 + 0.65 * vLoc.y);
  tx.rgb *= 1.0 - 0.24 * stk;
  float2 ed = min(vLoc, 1.0 - vLoc);
  float edg = 1.0 - smoothstep(0.004, 0.035, min(ed.x, ed.y * 0.5) + 0.018 * (nzB.r - 0.5));
  tx.rgb = lerp(tx.rgb, tx.rgb * 0.5 + float3(0.035, 0.032, 0.028), edg * 0.75);
  dc *= tx.rgb; sgR = 0.48 + 0.34 * nzB.g;
} else if (K == 2) {
  tx.rgb = lerp(tx.rgb, float3(lum, lum, lum), 0.45) * 0.66 + 0.05;
  tx.rgb = min(tx.rgb, float3(0.6, 0.6, 0.6)) * lerp(float3(1, 1, 1), dc / max(dot(dc, float3(0.333, 0.333, 0.333)), 0.05), 0.18);
  tx.rgb = lerp(tx.rgb, float3(1, 1, 1) * (dot(tx.rgb, float3(0.333, 0.333, 0.333)) * 1.08 + 0.02), 0.35 * smoothstep(0.3, 1.0, vLoc.y));
  float course = abs(frac(vWPs.y / 0.0762) - 0.5);
  tx.rgb *= 1.0 - 0.2 * smoothstep(0.4, 0.5, course);
  float peel = smoothstep(0.6, 0.76, nzA.r * 0.7 + nzB.g * 0.45 + 0.08 * (vLoc.y - 0.5));
  dc = lerp(tx.rgb, dc, min(1.0, peel * 0.9 + 0.1)); sgR = 0.88;
} else if (K == 3) {
  float dio = 1.0 - smoothstep(0.26, 0.42, max(abs(ledF.x), abs(ledF.y)));
  float grid = lerp(1.0, dio * 1.55, ledAA);
  sgE = tx.rgb * vSig.y * grid; dc *= tx.rgb * 0.12; sgR = 0.25;
} else if (K == 6) {
  float2 bf = frac(vMapUv) - 0.5; float bw = max(abs(ddx(vMapUv.x)) + abs(ddy(vMapUv.x)), abs(ddx(vMapUv.y)) + abs(ddy(vMapUv.y)));
  float bulb = 1.0 - smoothstep(0.2, 0.34, length(bf));
  bulb = lerp(bulb, 0.3, saturate(bw * 1.5 - 0.3));
  sgE = float3(1.0, 0.78, 0.46) * vSig.y * bulb; dc = lerp(dc, float3(0.9, 0.8, 0.6), bulb); sgR = lerp(0.5, 0.15, bulb);
} else if (K == 4) {
  sgE = tx.rgb * vSig.y; dc *= tx.rgb * 0.85; sgR = 0.35;
} else if (K == 7) {
  float st = vSig.y > 0.5 ? step(0.5, frac(vLoc.x * vSig.y)) : 0.0;
  dc = lerp(dc, float3(0.62, 0.58, 0.5), st * 0.85) * (0.82 + 0.3 * nzB.g) * (1.0 - 0.18 * smoothstep(0.5, 0.85, nzA.r));
  sgR = 0.88;
} else if (K == 8) {
  if (smoothstep(0.3, 0.5, lum) < 0.5) opv = 0.0;
  dc *= 0.8 + 0.3 * nzB.r; sgM = 0.85; sgR = 0.32 + 0.2 * nzA.g;
} else if (K == 9) {
  if (smoothstep(0.28, 0.42, lum) < 0.5) opv = 0.0;
  dc = tx.rgb * (0.78 + 0.25 * nzB.r); sgM = tx.r > tx.b * 1.4 ? 0.6 : 0.0; sgR = 0.38 + 0.2 * nzA.g;
  sgE = tx.rgb * 0.35 * nightk;
} else {
  float3 brd = vMapUv.x > 3.5 ? bR.rgb : bS.rgb;
  float lumL = smoothstep(0.1, 0.24, abs(lum - dot(brd, float3(0.2126, 0.7152, 0.0722))));
  tx.rgb = lerp(tx.rgb, float3(lum, lum, lum), 0.5);
  float bc = vWPs.y / 0.0762, row = floor(bc);
  float hx = (vWPs.x + vWPs.z) / 0.2032 + 0.5 * fmod(row, 2.0);
  float bh = frac(sin(dot(float2(floor(hx), row), float2(12.9898, 78.233))) * 43758.5453);
  float nearB = saturate(1.4 - 3.0 * max(abs(ddx(bc)) + abs(ddy(bc)), (abs(ddx(hx)) + abs(ddy(hx))) * 0.4));
  float wear = smoothstep(0.3, 0.85, nzA.r * 0.6 + nzB.b * 0.5 + 0.2 * (0.5 - vLoc.y));
  float cov = lerp(0.04, 0.97, lumL) * (1.0 - 0.7 * wear) * clamp(vSig.y * 1.7, 0.0, 1.2);
  float val = lerp(nzB.g, 0.5 * nzB.g + 0.5 * bh, nearB);
  float fb = frac(bc), fh = frac(hx);
  float mj = max(1.0 - smoothstep(0.035, 0.07, min(fb, 1.0 - fb)), 1.0 - smoothstep(0.012, 0.025, min(fh, 1.0 - fh)));
  if (val > cov || mj * nearB > 0.6) opv = 0.0;
  float3 gp = min(tx.rgb * 0.58 + 0.04, float3(0.46, 0.46, 0.46)) * lerp(float3(1, 1, 1), dc / max(dot(dc, float3(0.333, 0.333, 0.333)), 0.05), 0.45);
  dc = lerp(gp, dc, min(0.94, 0.5 + 0.35 * wear + 0.15 * bh * nearB + 0.2 * (1.0 - nearB))); sgR = 0.92;
}
Rough = sgR; Metal = sgM; Op = opv; Emis = sgE * 2.0;
return dc;""",
        [('tAds', 'tex', TEXA('Maps/assets_city_tex_ts_ads')), ('tSigns', 'tex', TEXA('Maps/assets_city_tex_ts_signs')), ('tArt', 'tex', TEXA('Maps/assets_city_tex_city_signart')), ('tNoise', 'tex', TEXA('noise')),
         ('uv0', 'uv', 0), ('uv1', 'uv', 1), ('uv2', 'uv', 2), ('vc', 'vc', None), ('wpos', 'wpos', None), ('nightk', 'mpc', 'NightK')],
        [('', 3, MP.MP_BASE_COLOR), ('Rough', 1, MP.MP_ROUGHNESS), ('Metal', 1, MP.MP_METALLIC), ('Op', 1, MP.MP_OPACITY_MASK), ('Emis', 3, MP.MP_EMISSIVE_COLOR)],
        blend='masked', world_normal=False)
    EAL.save_directory(MAT, only_if_is_dirty=False, recursive=True)
    # (r02) Manhattan land surface: block interiors dark grey gravel / paving, Central-Park-like rectangle grass
    make_material('M_CityLand', None, '''
float3 p = wpos * 0.01; float2 q = float2(p.x, p.y);  // UE cm -> m; UE (X, Y) = browser (x, z)
float n = Texture2DSample(tNoise, tNoiseSampler, q / 23.0).r * 0.6 + Texture2DSample(tNoise, tNoiseSampler, q / 4.1).g * 0.4;
bool park = q.x > -234.0 && q.x < 234.0 && q.y > -2151.0 && q.y < -569.0;
float3 c = park ? float3(0.12, 0.17, 0.07) * (0.8 + 0.4 * n) : float3(0.16, 0.155, 0.15) * (0.75 + 0.5 * n);
Rough = 0.9; return c;''',
        [('tNoise', 'tex', TEXA('noise')), ('wpos', 'wpos', None)], [('', 3, MP.MP_BASE_COLOR), ('Rough', 1, MP.MP_ROUGHNESS)], world_normal=False)
    # (r02) simple river water (P6 owns the real water): dark, glossy, two panning normal layers (world space, Z up)
    make_material('M_CityWater', None, '''
float2 q = wpos.xy * 0.01;
float3 n1 = Texture2DSample(tN, tNSampler, q / 37.0 + float2(0.013, 0.007) * t).xyz * 2.0 - 1.0;
float3 n2 = Texture2DSample(tN, tNSampler, q / 11.0 - float2(0.021, 0.011) * t).xyz * 2.0 - 1.0;
float2 xy = (n1.xy + n2.xy) * 0.18;
NormalW = normalize(float3(xy, 1.0)); Rough = 0.06;
return float3(0.018, 0.028, 0.03);''',
        [('tN', 'tex', TEXA('water_nrm')), ('wpos', 'wpos', None), ('t', 'time', None)],
        [('', 3, MP.MP_BASE_COLOR), ('Rough', 1, MP.MP_ROUGHNESS), ('NormalW', 3, MP.MP_NORMAL)])
    # (r02) hinterland boxes (horizon.js): wall / roof colour per instance (custom data 0-2 wall, 3-5 roof), floor bands
    make_material('M_CityHinter', None, '''
float3 wall = float3(w0, w1, w2), roof = float3(r0, r1, r2);
float band = 0.8 + 0.2 * step(0.5, frac(wpos.z * 0.01 / 3.4));
Rough = 0.9;
float3 hp = wpos * 0.01; float fl = frac(hp.z / 3.4), u = frac((hp.x + hp.y) / 2.6);
float w = step(0.35, fl) * step(fl, 0.85) * step(0.3, u) * step(u, 0.75);
float2 fw = fwidth(float2(hp.z / 3.4, (hp.x + hp.y) / 2.6)); w = lerp(w, 0.3, saturate(max(fw.x, fw.y) * 1.5));
float3 wc = lerp(wall, float3(0.08, 0.09, 0.1), w * 0.85) * (0.65 + 0.35 * smoothstep(0.0, 12.0, hp.z));  // horizon.js windows + grime
return wn.z > 0.5 ? roof : wc;''',
        [('w0', 'pcd', (0, 0)), ('w1', 'pcd', (1, 0)), ('w2', 'pcd', (2, 0)), ('r0', 'pcd', (3, 0)), ('r1', 'pcd', (4, 0)), ('r2', 'pcd', (5, 0)), ('wpos', 'wpos', None), ('wn', 'wn', None)],
        [('', 3, MP.MP_BASE_COLOR), ('Rough', 1, MP.MP_ROUGHNESS)], world_normal=False)
    make_material('M_CityCrown', None, '''
float3 p = wpos * 0.01;
float n = Texture2DSample(tNoise, tNoiseSampler, p.xy / 7.0 + p.z / 5.0).g * 0.6 + Texture2DSample(tNoise, tNoiseSampler, p.xy / 1.3).r * 0.4;
float up = saturate(wn.z * 0.5 + 0.5);
Rough = 0.8; Sub = float3(0.12, 0.2, 0.04);
return float3(0.07, 0.11, 0.035) * (0.6 + 0.8 * n) * (0.55 + 0.6 * up);''',
        [('tNoise', 'tex', TEXA('noise')), ('wpos', 'wpos', None), ('wn', 'wn', None)],
        [('', 3, MP.MP_BASE_COLOR), ('Rough', 1, MP.MP_ROUGHNESS), ('Sub', 3, MP.MP_SUBSURFACE_COLOR)], world_normal=False, shading=unreal.MaterialShadingModel.MSM_TWO_SIDED_FOLIAGE)
    log('materials done')

# ------------------------------------------------------------------------------------------------ meshes
man = json.load(open(os.path.join(EXPORT, 'manifest.json')))
KIND_MAT = {'signage': 'M_CitySignage', 'land': 'M_CityLand', 'facade': 'M_CityFacade', 'detail': 'M_CityDetail', 'roofs': 'M_CityRoof', 'asphalt': 'M_CityAsphalt', 'sidewalk': 'M_CitySidewalk'}
EMIS = ('tsScreens', 'tsTicker', 'tsNeon', 'tsLights', 'tsSigns', 'tsBands', 'signage', 'grandCentralGlow', 'parkPodiumGlow')
def mesh_pipeline(nanite):
    p = unreal.InterchangeGenericAssetsPipeline()
    p.common_meshes_properties.set_editor_properties({'recompute_normals': False, 'recompute_tangents': False, 'use_full_precision_u_vs': True,
        'remove_degenerates': False, 'vertex_color_import_option': unreal.InterchangeVertexColorImportOption.IVCIO_REPLACE})
    p.mesh_pipeline.set_editor_properties({'generate_lightmap_u_vs': False, 'build_nanite': nanite})
    p.material_pipeline.set_editor_property('import_materials', False)
    p.material_pipeline.texture_pipeline.set_editor_property('import_textures', False)
    return p
def mi_for(rec):
    """material instance of M_CityVC for a generic mesh (colour / roughness / map from the three.js material)"""
    mat = rec.get('mat') or {}
    key = rec['name']
    path = f'{MAT}/Inst/MI_{key}'
    if EAL.does_asset_exist(path): return load(path)
    mi = at.create_asset('MI_' + key, MAT + '/Inst', unreal.MaterialInstanceConstant, unreal.MaterialInstanceConstantFactoryNew())
    mel.set_material_instance_parent(mi, load(MAT + ('/M_CityProp' if rec.get('proto') and 'aPart.x' in rec.get('uv', []) else '/M_CityVC')))
    col = mat.get('color') or [1, 1, 1]
    if key.endswith('_bark'): col = [0.33, 0.29, 0.25]  # ez-tree bark (browser: bark texture + vertex AO)
    if key.endswith('_bark'): mel.set_material_instance_vector_parameter_value(mi, 'Tint', unreal.LinearColor(*col, 1))
    if not rec.get('proto'):
        mel.set_material_instance_vector_parameter_value(mi, 'Tint', unreal.LinearColor(col[0], col[1], col[2], 1))
        mel.set_material_instance_scalar_parameter_value(mi, 'RoughP', float(mat.get('roughness') or 0.7))
        mel.set_material_instance_scalar_parameter_value(mi, 'MetalP', float(mat.get('metalness') or 0.0))
        if key.startswith(EMIS) or any(key.startswith(e) for e in EMIS): mel.set_material_instance_scalar_parameter_value(mi, 'EmisGain', 2.0)
        if mat.get('alphaTest') or key == 'markings': mel.set_material_instance_scalar_parameter_value(mi, 'AlphaCut', 0.5)
    u = mat.get('map')
    if u:
        rel = u.split('5202/', 1)[-1].split('?')[0].replace('/', '_').rsplit('.', 1)[0]
        tp = f'{ROOT}/Textures/Maps/{rel}'
        if EAL.does_asset_exist(tp):
            mel.set_material_instance_texture_parameter_value(mi, 'Map', load(tp)); mel.set_material_instance_scalar_parameter_value(mi, 'UseMap', 1.0)
    EAL.save_asset(path)
    return mi

def keep_mesh(rec):
    m = rec.get('mat') or {}
    if rec['kind'] in KIND_MAT or rec['name'] == 'markings': return True
    return not m.get('transparent')  # additive / multiply overlays (spill, halos, AO, grime) are left out for now

sms = ueditor = unreal.get_editor_subsystem(unreal.StaticMeshEditorSubsystem)
def finish_mesh(sm, mat, collide, nanite=False):
    sm.set_material(0, mat)
    ns = sm.get_editor_property('nanite_settings')  # Nanite quantises UVs: the facade / roof data channels need full precision
    if ns.enabled != nanite: ns.enabled = nanite; sm.set_editor_property('nanite_settings', ns)
    bs = sms.get_lod_build_settings(sm, 0)
    bs.set_editor_property('use_full_precision_u_vs', True); bs.set_editor_property('generate_lightmap_u_vs', False)
    bs.set_editor_property('recompute_normals', False); bs.set_editor_property('recompute_tangents', False)
    sms.set_lod_build_settings(sm, 0, bs)
    if collide:
        bsetup = sm.get_editor_property('body_setup')
        if bsetup: bsetup.set_editor_property('collision_trace_flag', unreal.CollisionTraceFlag.CTF_USE_COMPLEX_AS_SIMPLE)

if 'mesh' in STEPS:
    recs = [r for r in man['meshes'] if keep_mesh(r)]
    for nan in (False, True):
        group = [r for r in recs if (r['kind'] == 'detail') == nan]
        dest = ROOT + '/Meshes'
        import_files([os.path.join(EXPORT, r['file']) for r in group], dest + '/_in', mesh_pipeline(nan))
    n = 0
    for r in recs:
        base = os.path.basename(r['file'])[:-4]
        src = f'{ROOT}/Meshes/_in/{base}/StaticMeshes/{base}'
        dst = f'{ROOT}/Meshes/{r["kind"]}/SM_{base}'
        if not EAL.does_asset_exist(src): log('MISSING import', src); continue
        EAL.rename_asset(src, dst)
        sm = load(dst)
        mat = load(f'{MAT}/{KIND_MAT[r["kind"]]}') if r['kind'] in KIND_MAT else (load(MAT + '/M_CityFrame') if r['name'].startswith('tsFrames') else mi_for(r))
        finish_mesh(sm, mat, r['kind'] in ('facade', 'roofs', 'asphalt', 'sidewalk', 'detail') and not r.get('lod'), nanite=r['kind'] == 'detail')
        EAL.save_asset(dst); n += 1
    EAL.delete_directory(ROOT + '/Meshes/_in')
    log('meshes', n)

# ------------------------------------------------------------------------------------------------ prototypes (instanced props / trees)
SKIP_POOL = ('Far', '_mid', '_xfar', 'lampPool', 'propContactAO', 'trees_', 'trunks_', 'roofplants', 'hvac_', 'vents_', 'dish_', 'antenna_', 'flags')
CROWN = ('trees_park_crownfar', 'trees_elm_crownfar', 'trees_conifer_crownfar')  # (r03) opaque canopy mass inside the park LOD1 trees
protos = [p for p in man['protos'] if p['name'] in CROWN or (not any(s in p['name'] for s in SKIP_POOL) and not p['name'].endswith('_far'))]
LEAFY = lambda n: 'leaves' in n
if 'proto' in STEPS:
    import_files([os.path.join(EXPORT, p['file']) for p in protos], ROOT + '/Props/_in', mesh_pipeline(True))
    for p in protos:
        src = f'{ROOT}/Props/_in/{p["name"]}/StaticMeshes/{p["name"]}'; dst = f'{ROOT}/Props/SM_{p["name"]}'
        if not EAL.does_asset_exist(src): log('MISSING proto', src); continue
        EAL.rename_asset(src, dst); sm = load(dst)
        if LEAFY(p['name']):
            mi = at.create_asset('MI_' + p['name'], MAT + '/Inst', unreal.MaterialInstanceConstant, unreal.MaterialInstanceConstantFactoryNew())
            mel.set_material_instance_parent(mi, load(MAT + '/M_CityLeaves'))
            u = (p.get('mat') or {}).get('map')
            if u:
                rel = u.split('5202/', 1)[-1].replace('/', '_').rsplit('.', 1)[0]
                if EAL.does_asset_exist(f'{ROOT}/Textures/Maps/{rel}'): mel.set_material_instance_texture_parameter_value(mi, 'Map', load(f'{ROOT}/Textures/Maps/{rel}'))
            EAL.save_asset(mi.get_path_name())
        else:
            mi = load(MAT + '/M_CityHinter') if p['name'] == 'hinterland' else (load(MAT + '/M_CityCrown') if p['name'] in CROWN else mi_for({**p, 'proto': True}))
        finish_mesh(sm, mi, False, nanite=True)
        EAL.save_asset(dst)
    EAL.delete_directory(ROOT + '/Props/_in')
    log('protos', len(protos))

# ------------------------------------------------------------------------------------------------ maps
def U(x, y, z): return unreal.Vector(x * 100.0, z * 100.0, y * 100.0)
def look_rot(p, t):
    d = unreal.Vector(t.x - p.x, t.y - p.y, t.z - p.z)
    yaw = math.degrees(math.atan2(d.y, d.x)); pitch = math.degrees(math.atan2(d.z, math.hypot(d.x, d.y)))
    return unreal.Rotator(roll=0.0, pitch=pitch, yaw=yaw)
eas = unreal.get_editor_subsystem(unreal.EditorActorSubsystem)
les = unreal.get_editor_subsystem(unreal.LevelEditorSubsystem)
def spawn(cls, loc=unreal.Vector(0, 0, 0), rot=unreal.Rotator(0, 0, 0), label=None, folder=None):
    a = eas.spawn_actor_from_class(cls, loc, rot)
    if label: a.set_actor_label(label)
    if folder: a.set_folder_path(folder)
    return a
sds = unreal.get_engine_subsystem(unreal.SubobjectDataSubsystem)
def add_component(actor, cls):
    root = sds.k2_gather_subobject_data_for_instance(actor)[0]
    h, fail = sds.add_new_subobject(unreal.AddNewSubobjectParams(parent_handle=root, new_class=cls, blueprint_context=None))
    return unreal.SubobjectDataBlueprintFunctionLibrary.get_object(unreal.SubobjectDataBlueprintFunctionLibrary.get_data(h))

SHOTS = json.load(open(os.path.join(os.path.dirname(os.path.abspath(__file__)) if '__file__' in globals() and os.path.exists(os.path.join(os.path.dirname(os.path.abspath(__file__)), 'city_shots.json')) else '/Users/midir/sm2-n1/city/unreal/WebHomage/Scripts', 'city_shots.json')))

def open_level(path):
    """idempotent: an existing map is opened and emptied (deleting maps pops a modal dialog), else created"""
    if EAL.does_asset_exist(path):
        unreal.EditorLoadingAndSavingUtils.load_map(path)
        for a in eas.get_all_level_actors():
            if a.get_class().get_name() not in ('WorldSettings', 'Brush', 'DefaultPhysicsVolume', 'GameplayDebuggerCategoryReplicator', 'WorldDataLayers', 'WorldPartitionMiniMap'):
                eas.destroy_actor(a)
    else:
        les.new_level(path)
    return unreal.get_editor_subsystem(unreal.UnrealEditorSubsystem).get_editor_world()

def build_geo_level(path):
    open_level(path)
    recs = [r for r in man['meshes'] if keep_mesh(r)]
    for r in recs:
        base = os.path.basename(r['file'])[:-4]; sp = f'{ROOT}/Meshes/{r["kind"]}/SM_{base}'
        if not EAL.does_asset_exist(sp): continue
        a = spawn(unreal.StaticMeshActor, U(r['center'][0], 0, r['center'][2]), label=base, folder='City/' + r['kind'])
        smc = a.static_mesh_component; smc.set_static_mesh(load(sp))
        a.set_mobility(unreal.ComponentMobility.STATIC)
    # instanced props / trees from layout.json pool items
    L = json.load(open(os.path.join(EXPORT, 'layout.json')))
    ni = 0
    for p in protos:
        pool = p['src']; items = (L['instances'].get(pool) or {}).get('items') or []
        sp = f'{ROOT}/Props/SM_{p["name"]}'
        if not items or not EAL.does_asset_exist(sp): continue
        a = spawn(unreal.Actor, unreal.Vector(0, 0, 0), label='ISM_' + p['name'], folder='City/Props')
        c = add_component(a, unreal.HierarchicalInstancedStaticMeshComponent)
        c.set_static_mesh(load(sp)); c.set_editor_property('num_custom_data_floats', 4)
        xs = []
        for it in items:
            s = it.get('s', 1.0); s3 = it.get('s3') or [1, 1, 1]
            # browser: rotation about +y by ry (right-handed, y up). UE: yaw about Z with Y = z mirrored handedness -> yaw = -ry
            rot = unreal.Rotator(roll=math.degrees(it.get('rz', 0.0)), pitch=-math.degrees(it.get('rx', 0.0)), yaw=-math.degrees(it.get('ry', 0.0)))
            if p["name"] in CROWN: s *= 1.0
            xs.append(unreal.Transform(U(it['x'], it['y'], it['z']), rot, unreal.Vector(s * s3[0], s * s3[2], s * s3[1])))
        ids = c.add_instances(xs, True, True)
        for k, it in enumerate(items):
            tint = ((it.get('e') or {}).get('aTint')) or [1, 1, 1]; st = (it.get('e') or {}).get('aState', 0)
            for j, v in enumerate((tint[0], tint[1], tint[2], st if isinstance(st, (int, float)) else 0)): c.set_custom_data_value(k, j, float(v), False)
        ni += len(items)
    # ground under everything (lot interiors / plazas never exported as geometry)
    # (r02) rivers / harbour: one water plane at the browser's G.WATER_Y (-1.6 m), 60 km wide (land meshes sit above it)
    g = spawn(unreal.StaticMeshActor, U(0, -1.6, 0), label='WaterPlane', folder='City')
    g.static_mesh_component.set_static_mesh(load('/Engine/BasicShapes/Plane')); g.set_actor_scale3d(unreal.Vector(60000, 60000, 1))
    g.static_mesh_component.set_material(0, load(MAT + '/M_CityWater'))
    # (r02) hinterland (horizon.js): 5-sided boxes to the horizon, per-instance colours
    hp = os.path.join(EXPORT, 'hinterland.json')
    if os.path.exists(hp) and EAL.does_asset_exist(ROOT + '/Props/SM_hinterland'):
        H = json.load(open(hp))['items']
        a = spawn(unreal.Actor, unreal.Vector(0, 0, 0), label='ISM_hinterland', folder='City/Far')
        c = add_component(a, unreal.HierarchicalInstancedStaticMeshComponent)
        c.set_static_mesh(load(ROOT + '/Props/SM_hinterland')); c.set_editor_property('num_custom_data_floats', 6)
        c.set_editor_property('cast_shadow', False)
        c.add_instances([unreal.Transform(U(h[0], h[1], h[2]), unreal.Rotator(0, 0, -math.degrees(h[6])), unreal.Vector(h[3], h[5], h[4])) for h in H], False, True)
        for k, h in enumerate(H):
            for j in range(6): c.set_custom_data_value(k, j, float(h[7 + j]), False)
        log('hinterland', len(H))
    les.save_current_level()
    log('geo level', path, len(recs), 'meshes', ni, 'instances')

def add_lighting(sun_pitch, sun_yaw, sunset=False):
    sun = spawn(unreal.DirectionalLight, unreal.Vector(0, 0, 50000), unreal.Rotator(roll=0, pitch=sun_pitch, yaw=sun_yaw), 'Sun', 'Lighting')
    lc = sun.light_component
    lc.set_editor_property('intensity', 6.0 if not sunset else 4.0)
    lc.set_editor_property('atmosphere_sun_light', True); lc.set_mobility(unreal.ComponentMobility.MOVABLE)
    spawn(unreal.SkyAtmosphere, unreal.Vector(0, 0, 0), label='SkyAtmosphere', folder='Lighting')
    sl = spawn(unreal.SkyLight, unreal.Vector(0, 0, 2000), label='SkyLight', folder='Lighting')
    sl.light_component.set_editor_property('real_time_capture', True); sl.light_component.set_mobility(unreal.ComponentMobility.MOVABLE)
    fog = spawn(unreal.ExponentialHeightFog, unreal.Vector(0, 0, 0), label='HeightFog', folder='Lighting')
    fc = fog.component; fc.set_editor_property('fog_density', 0.006 if not sunset else 0.009); fc.set_editor_property('fog_height_falloff', 0.12)
    fc.set_editor_property('start_distance', 40000.0)  # (r02) clear near field, aerial haze band toward the horizon
    fc.set_editor_property('fog_inscattering_luminance', unreal.LinearColor(0.32, 0.4, 0.52, 1) if not sunset else unreal.LinearColor(0.9, 0.55, 0.35, 1))
    spawn(unreal.VolumetricCloud, unreal.Vector(0, 0, 0), label='Clouds', folder='Lighting')
    ppv = spawn(unreal.PostProcessVolume, unreal.Vector(0, 0, 0), label='PPV', folder='Lighting')
    ppv.set_editor_property('unbound', True)
    st = ppv.get_editor_property('settings')  # simple, deterministic exposure for the city test maps (P4 owns the final look)
    for k, v in (('auto_exposure_method', unreal.AutoExposureMethod.AEM_MANUAL), ('auto_exposure_bias', 2.0 if not sunset else 2.3),
                 ('auto_exposure_apply_physical_camera_exposure', False)):
        st.set_editor_property('override_' + k, True); st.set_editor_property(k, v)
    ppv.set_editor_property('settings', st)

if 'map' in STEPS:
    unreal.EditorAssetLibrary.make_directory(TESTS)
    build_geo_level(TESTS + '/City_Midtown_Geo')
    # playable test map: geometry (streamed, always loaded) + day light + PlayerStart on the 5th-Avenue-like crosswalk
    for mp, sun, cam in [('City_Midtown', (-42, 135), None)] + [(f'City_View_{s["id"]}', tuple(s.get('sun', (-42, 135))), s) for s in SHOTS]:
        world = open_level(f'{TESTS}/{mp}')
        if not any('City_Midtown_Geo' in l.get_path_name() for l in unreal.EditorLevelUtils.get_levels(world)):
            unreal.EditorLevelUtils.add_level_to_world(world, TESTS + '/City_Midtown_Geo', unreal.LevelStreamingAlwaysLoaded)
        if not les.set_current_level_by_name(mp): log('WARN could not make persistent level current', mp)  # new actors go to the persistent level, not the streamed geometry
        add_lighting(sun[0], sun[1], sunset=bool(cam and cam.get('sunset')))
        ps = SHOTS[0]['player'] if cam is None else cam.get('player', SHOTS[0]['player'])
        spawn(unreal.PlayerStart, U(ps[0], ps[1] + 1.0, ps[2]), unreal.Rotator(0, 0, -90), 'PlayerStart')
        if cam:
            p, t = U(*cam['pos']), U(*cam['target'])
            ca = spawn(unreal.CameraActor, p, look_rot(p, t), 'ShotCam_' + cam['id'])
            ca.camera_component.set_editor_property('field_of_view', cam.get('fov', 70))
            ca.camera_component.set_editor_property('constrain_aspect_ratio', False)
            ca.set_editor_property('auto_activate_for_player', unreal.AutoReceiveInput.PLAYER0)
        unreal.EditorLoadingAndSavingUtils.save_map(world, f'{TESTS}/{mp}')
        log('map', mp)
log('DONE')
