// Homage fan game. Not an official Marvel, Sony or Insomniac game; no affiliation. See DISCLAIMER.md.
// P6 City life: dump the browser road network (src/world/npc/roads.js buildRoads(), the SAME data the browser traffic and
// crowd use) for the Midtown 3x3 region as two small text files the Unreal build feeds to the life actors:
//   unreal/WebHomage/Scripts/life_data/lanes.txt   lane links + junction connectors + connector conflicts + signal nodes
//   unreal/WebHomage/Scripts/life_data/walk.txt    pedestrian graph: sidewalk corners, sidewalk edges, crosswalk edges
// Frame: browser metres (x east, z south). The Unreal side maps (x, z) -> UE (100 x, 100 z) cm (see docs/night1/city/EXPORT.md).
//
//   node tools/life/export_lanes.mjs [--region x0,z0,x1,z1]
//
// lanes.txt (one record per line, '#' comments):
//   N id x z hw hz sig                                node: centre, avenue / street half widths, signalised (avenue x street) 0/1
//   L id from to ax az dx dz len kind lane axis sig noPark narrow p0 p1 ..   link (lane centre line start, unit dir, length); kind 0 av 1 st 2 ws 3 diag;
//                                                    axis 0 av 1 st (signal phase axis); pN = parking side lateral offsets right of travel
//   C id fromLink toLink turn len n x0 z0 ... xN zN   connector through the junction box (n polyline points); turn 0 S 1 L 2 R
//   X id a b c ...                                   connector ids whose paths cross / merge with connector id (same node, other approach)
// Signal phases (props.js phase(), 40 s cycle) are compiled into the C++ (WHLifeTraffic.cpp), not exported.
//
// walk.txt:
//   P id x z                                          sidewalk corner point
//   E id a b kind axis len side                       edge a-b; kind 0 sidewalk 1 crosswalk; axis (crosswalks) 0 = crossed by avenue traffic, 1 = crossed by street traffic;
//                                                     side +1 / -1: the roadway lies to the right / left of a -> b (sidewalk edges), 0 crosswalk
//   B x0 z0 x1 z1                                     region bounds
//
// parked.txt (needs --layout <export>/layout.json for the curb props):
//   type x z yawDeg r g b flags                       parked car / curb taxi / double-parked truck / bus at its stop (type = index in the C++ order taxi, taxi_hy,
//                                                    taxi_mv, taxi_gr, sedan, hatch, sedan2, cross, suv, suv2, pickup, van, truck, bus, tour; colour linear; flags 1 = hazards)
import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

globalThis.location = { search: '', href: 'http://localhost/', hash: '', pathname: '/' };
globalThis.window = globalThis;
globalThis.document = { createElement: () => ({ getContext: () => ({}), style: {} }), addEventListener() {} };

const HERE = path.dirname(fileURLToPath(import.meta.url));
const ROOT = path.resolve(HERE, '../..');
const arg = (k, d) => { const i = process.argv.indexOf('--' + k); return i > 0 ? process.argv[i + 1] : d; };
const [rx0, rz0, rx1, rz1] = arg('region', '-262,-512,514,256').split(',').map(Number);
const LAYOUT = arg('layout', '');
const OUT = path.join(ROOT, 'unreal/WebHomage/Scripts/life_data');
fs.mkdirSync(OUT, { recursive: true });

const { buildRoads, connector } = await import(path.join(ROOT, 'src/world/npc/roads.js'));
const { G, streetsAt, mulberry32, bikeLaneAt, islandNear, DIAG_SEGS, diagD } = await import(path.join(ROOT, 'src/world/layout.js'));
const R = buildRoads();
const inR = (x, z, m = 0) => x >= rx0 - m && x <= rx1 + m && z >= rz0 - m && z <= rz1 + m;
const f = (v, d = 2) => (+v.toFixed(d)).toString();

// ------------------------------------------------------------------ lanes
const links = R.links.filter((l) => inR(l.ax, l.az) && inR(l.ax + l.dx * l.len, l.az + l.dz * l.len) && !l.bridge && !l.vmap && l.len > 4);
const ids = new Set(links.map((l) => l.id));
const nodeIds = new Set();
for (const l of links) { nodeIds.add(l.from); nodeIds.add(l.to); }
const kindOf = (l) => (l.diag ? 3 : l.kind === 'ws' ? 2 : l.kind === 'st' ? 1 : 0);
const lines = ['# P6 city life lanes: generated by tools/life/export_lanes.mjs from src/world/npc/roads.js (do not edit)'];
for (const nid of [...nodeIds].sort((a, b) => a - b)) {
  const n = R.nodes[nid]; if (!n) continue;
  lines.push(`N ${n.id} ${f(n.x)} ${f(n.z)} ${f(n.hw || 0)} ${f(n.hz || 0)} ${n.av && n.st ? 1 : 0}`);
}
for (const l of links) {
  const sig = l.signal ? 1 : 0, axis = l.axis === 'st' ? 1 : 0;
  lines.push(`L ${l.id} ${l.from} ${l.to} ${f(l.ax)} ${f(l.az)} ${f(l.dx, 4)} ${f(l.dz, 4)} ${f(l.len)} ${kindOf(l)} ${l.lane || 0} ${axis} ${sig} ${l.noPark ? 1 : 0} ${l.narrow ? 1 : 0}` +
    (l.parkSides ? ' ' + l.parkSides.map((v) => f(v)).join(' ') : ''));
}
const conns = []; // {id, L, O, turn, P, len, poly}
let cid = 0;
for (const l of links) {
  for (const o of l.out || []) {
    if (!ids.has(o.link.id)) continue;
    const C = connector(l, o.link, o.turn);
    if (!C || !C.P) continue;
    const poly = [];
    const N = Math.max(4, Math.min(24, Math.ceil(C.len / 2.5)));
    for (let i = 0; i <= N; i++) { const t = i / N, u = 1 - t, P = C.P; poly.push([u * u * u * P[0] + 3 * u * u * t * P[2] + 3 * u * t * t * P[4] + t * t * t * P[6], u * u * u * P[1] + 3 * u * u * t * P[3] + 3 * u * t * t * P[5] + t * t * t * P[7]]); }
    let len = 0; for (let i = 1; i < poly.length; i++) len += Math.hypot(poly[i][0] - poly[i - 1][0], poly[i][1] - poly[i - 1][1]);
    conns.push({ id: cid++, L: l, O: o.link, turn: o.turn === 'S' ? 0 : o.turn === 'L' ? 1 : 2, poly, len });
  }
}
for (const c of conns) lines.push(`C ${c.id} ${c.L.id} ${c.O.id} ${c.turn} ${f(c.len)} ${c.poly.length} ${c.poly.map((p) => f(p[0]) + ' ' + f(p[1])).join(' ')}`);
// conflicts: connectors of the same node from DIFFERENT approach links whose paths come within 2.3 m (or that merge into one out link)
const byNode = new Map();
for (const c of conns) { const k = c.L.to; if (!byNode.has(k)) byNode.set(k, []); byNode.get(k).push(c); }
const dense = (poly) => { const o = []; for (let i = 1; i < poly.length; i++) { const a = poly[i - 1], b = poly[i], n = Math.max(1, Math.ceil(Math.hypot(b[0] - a[0], b[1] - a[1]) / 0.5)); for (let k = 0; k < n; k++) o.push([a[0] + (b[0] - a[0]) * k / n, a[1] + (b[1] - a[1]) * k / n]); } o.push(poly[poly.length - 1]); return o; };
let nconf = 0;
for (const cs of byNode.values()) {
  const D = cs.map((c) => dense(c.poly));
  for (let i = 0; i < cs.length; i++) {
    const conf = [];
    for (let j = 0; j < cs.length; j++) {
      if (i === j || cs[i].L === cs[j].L) continue;
      let hit = cs[i].O === cs[j].O;
      for (let a = 0; a < D[i].length && !hit; a++) for (let b = 0; b < D[j].length; b++) if (Math.hypot(D[i][a][0] - D[j][b][0], D[i][a][1] - D[j][b][1]) < 2.3) { hit = true; break; }
      if (hit) conf.push(cs[j].id);
    }
    if (conf.length) { lines.push(`X ${cs[i].id} ${conf.join(' ')}`); nconf += conf.length; }
  }
}
fs.writeFileSync(path.join(OUT, 'lanes.txt'), lines.join('\n') + '\n');
console.log(`lanes.txt: ${nodeIds.size} nodes, ${links.length} links, ${conns.length} connectors, ${nconf} conflict pairs`);


// ------------------------------------------------------------------ parked cars (port of traffic.js parkedFor)
{
  const VT = [['taxi', 5.39, 1.99], ['taxi_hy', 4.54, 1.76], ['taxi_mv', 5.08, 1.99], ['taxi_gr', 4.86, 1.84], ['sedan', 4.85, 1.84], ['hatch', 4.26, 1.79], ['sedan2', 4.9, 1.85],
    ['cross', 4.6, 1.86], ['suv', 4.9, 1.95], ['suv2', 5.35, 2.03], ['pickup', 5.9, 2.03], ['van', 5.98, 2.06], ['truck', 7.3, 2.3], ['bus', 12.2, 2.55], ['tour', 11, 2.55]];
  const TI = Object.fromEntries(VT.map((v, i) => [v[0], i]));
  const lin = (c) => [((c >> 16) & 255) / 255, ((c >> 8) & 255) / 255, (c & 255) / 255].map((v) => Math.pow(v, 2.2));
  const CAR_COLORS = [0x0e0e0f, 0x151517, 0x1b1c1f, 0x101418, 0xe2e2df, 0xd8d8d4, 0xcfcfca, 0xe6e3da, 0xa9adb1, 0x9c9fa3, 0xb7b9bb, 0x8e9296, 0x6d7074, 0x55585c, 0x44474b,
    0x1b2a4a, 0x223a63, 0x2f4c7a, 0x5a1216, 0x6e1a1a, 0x8a1f1f, 0xb3a98f, 0x9b8f75, 0x2c3d2e, 0x44563f, 0x6b86a0, 0x4a3a2c, 0x3b4450, 0x7c8a8f, 0x2a2d33];
  const PAL = CAR_COLORS.map(lin), TAXI = lin(0xf5a900), TAXI_GR = lin(0x9aae4c);
  const VANC = [0xd6d6d2, 0xcfccc4, 0xc9c9c7, 0xd9d7d0].map(lin), LIVERY = [0x0b0b0c, 0x0e0e10, 0x121315, 0x0d1014].map(lin);
  const colorOf = (type, r) => type === 'taxi_gr' ? (r < 0.3 ? TAXI_GR : TAXI) : type.startsWith('taxi') ? TAXI
    : (type === 'suv2' && r < 0.7) || (type === 'sedan2' && r < 0.4) || (type === 'suv' && r < 0.3) ? LIVERY[Math.floor(r * 97) % LIVERY.length]
    : (type === 'truck' || type === 'van') ? VANC[Math.floor(r * VANC.length)] : type === 'tour' ? lin(0xb3121a) : type === 'bus' ? lin(0xe4e4e0) : PAL[Math.floor(r * PAL.length) % PAL.length];
  // curb props that block a parking spot (sampled from the P1 export)
  const BLOCK = ['hydrant', 'meter', 'signpole', 'busstop', 'shelter', 'cone', 'barrier', 'drum', 'dumpster', 'rolloff', 'sawhorse', 'kiosk', 'stack', 'pit', 'pit2', 'subway', 'subwaypit', 'newsbox', 'payphone', 'bikerack', 'planter', 'mailbox', 'bench', 'trash', 'lamp', 'post', 'mast'];
  let props = [];
  if (LAYOUT && fs.existsSync(LAYOUT)) {
    const L = JSON.parse(fs.readFileSync(LAYOUT, 'utf8')).instances || {};
    for (const k of BLOCK) for (const it of (L[k]?.items || [])) props.push([it.x, it.z, k]);
  }
  const propNear = (x, z, r) => { for (const p of props) if (Math.abs(p[0] - x) < r && Math.abs(p[1] - z) < r && Math.hypot(p[0] - x, p[1] - z) < r) return true; return false; };
  const connPts = conns.map((c) => c.poly);
  const nearTurn = (x, z, r) => { for (const poly of connPts) for (const q of poly) if (Math.abs(q[0] - x) < r && Math.abs(q[1] - z) < r && Math.hypot(q[0] - x, q[1] - z) < r) return true; return false; };
  const onDiag = (x, z, pad) => { for (const g of DIAG_SEGS) { const u = (x - g.ax) * g.ux + (z - g.az) * g.uz; if (u > -pad && u < g.len + pad && Math.abs(diagD(g, x, z)) < g.hw + pad) return true; } return false; };
  const inRegion = (x, z) => x > rx0 + 3 && x < rx1 - 3 && z > rz0 + 3 && z < rz1 - 3;
  const out = ['# P6 city life parked cars: generated by tools/life/export_lanes.mjs (do not edit)  columns: type x z yawDeg r g b flags'];
  let nPark = 0, nTaxi = 0, nBlocked = 0;
  for (const L of links) {
    const kind = L.kind === 'ws' ? 'ws' : L.kind;
    if (L.noPark || (L.kind !== 'st' && L.lane !== 1)) continue;
    const rng = mulberry32((L.id * 48271 + 11) >>> 0);
    const sides = L.parkSides || (L.kind === 'st' ? [3.9, -3.9] : [3.8]);
    const rx = -L.dz, rz = L.dx, hd = Math.atan2(L.dz, L.dx);
    for (const lat of sides) {
      if (rng() < 0.12) continue;
      const off = L.parkSides ? lat : L.kind === 'st' ? lat - 0.6 : lat;
      const special = [];
      {
        const r2 = mulberry32((L.id * 69621 + (lat > 0 ? 7 : 3)) >>> 0);
        const av = L.kind !== 'st';
        const put = (type, sAt, latOff, haz) => {
          const T = VT[TI[type]];
          if (sAt < 8 || sAt > L.len - 10) return;
          const x = L.ax + L.dx * sAt + rx * latOff, z = L.az + L.dz * sAt + rz * latOff;
          if (propNear(x, z, 1.5) || islandNear(x, z, 2.8) || bikeLaneAt(x, z) || onDiag(x, z, T[1] / 2 + 3) || nearTurn(x, z, T[1] / 2 + 1.6) || !inRegion(x, z)) { nBlocked++; return; }
          special.push({ type, len: T[1], x, z, yaw: hd + (r2() - 0.5) * 0.05, color: colorOf(type, r2()), haz, s: sAt });
        };
        const inset = (d, min) => Math.sign(off) * Math.max(Math.abs(off) - d, min);
        if (r2() < (av ? 0.2 : 0.26) && !L.narrow) put('truck', 12 + r2() * (L.len - 30), inset(1.05, 2.45), true);
        if (r2() < 0.42 && !L.narrow) put(['taxi_hy', 'taxi_mv', 'taxi_gr', 'taxi_hy'][(L.id * 7 + (lat > 0 ? 1 : 0)) % 4], 10 + r2() * (L.len - 25), inset(0.35, 2.35), true);
        if (av && r2() < 0.14 && L.len - 5 > 30) put('bus', L.len - 5 - 12 - r2() * 8, inset(0.4, 2.65), false);
      }
      const rows = [];
      for (const q of special) rows.push(q);
      for (let s = 9 + rng() * 5; s < L.len - 12; s += 5.9 + rng() * 2.4) {
        if (rng() < (L.kind === 'st' ? 0.16 : 0.28)) continue;
        if (special.some((q) => Math.abs(q.s - s) < q.len / 2 + 3.4)) continue;
        const r = rng();
        let type = r < 0.08 ? 'taxi' : r < 0.52 ? 'sedan' : r < 0.93 ? 'suv' : 'truck';
        { const h = Math.abs(Math.sin(L.id * 12.9898 + s * 78.233) * 43758.5453) % 1;
          if (type === 'taxi') type = h < 0.15 ? 'taxi' : h < 0.55 ? 'taxi_hy' : h < 0.8 ? 'taxi_mv' : 'taxi_gr';
          else if (type === 'sedan') type = h < 0.42 ? 'sedan' : h < 0.74 ? 'sedan2' : 'hatch';
          else if (type === 'suv') type = h < 0.32 ? 'suv' : h < 0.6 ? 'cross' : h < 0.88 ? 'suv2' : 'pickup';
          else if (type === 'truck') type = h < 0.45 ? 'van' : 'truck'; }
        const T = VT[TI[type]];
        if (type === 'truck' || type === 'van' || type === 'pickup') s += 1.3;
        const x = L.ax + L.dx * s + rx * off + (rng() - 0.5) * 0.2, z = L.az + L.dz * s + rz * off + (rng() - 0.5) * 0.2;
        const yaw = hd + (rng() - 0.5) * 0.04, color = colorOf(type, rng());
        if (type === 'truck') s += 2.5; else if (type === 'van' || type === 'pickup') s += 0.6;
        if (propNear(x, z, 1.5) || islandNear(x, z, 2.8) || bikeLaneAt(x, z) || onDiag(x, z, T[1] / 2 + 3) || nearTurn(x, z, T[1] / 2 + 1.6) || !inRegion(x, z)) { nBlocked++; continue; }
        rows.push({ type, x, z, yaw, color, haz: false });
      }
      for (const q of rows) { out.push(`${TI[q.type]} ${f(q.x)} ${f(q.z)} ${f(q.yaw * 180 / Math.PI, 1)} ${q.color.map((v) => f(v, 4)).join(' ')} ${q.haz ? 1 : 0}`); nPark++; if (TI[q.type] <= 3) nTaxi++; }
    }
  }
  fs.writeFileSync(path.join(OUT, 'parked.txt'), out.join('\n') + '\n');
  console.log(`parked.txt: ${nPark} parked vehicles (${nTaxi} taxis), ${nBlocked} spots blocked by curb props / junction paths / regions; props considered ${props.length}`);
}

// ------------------------------------------------------------------ pedestrian graph
// Corners of every grid junction (avenue x street): the four sidewalk corner points; sidewalk edges along the avenue / street
// sides between neighbouring junctions; crosswalk edges across each existing leg. Every point is checked against the browser
// layout (streetsAt): sidewalk points must be 'sidewalk', crosswalk samples must be asphalt ('avenue' / 'street' / 'intersection').
const WM = 1.0; // keep points this far inside the region
const nodes = R.nodes.filter((n) => n && n.av && n.st && n.i >= 0 && n.j >= 0);
const cornerKey = (n, sx, sz) => `${n.id}:${sx}:${sz}`;
const corners = new Map(); const P = [];
const isWalk = (x, z) => streetsAt(x, z).type === 'sidewalk';
const isRoad = (x, z) => { const t = streetsAt(x, z).type; return t === 'avenue' || t === 'street' || t === 'intersection'; };
for (const n of nodes) {
  for (const sx of [-1, 1]) for (const sz of [-1, 1]) {
    let ok = null;
    // walk outward from the kerb until the point is a sidewalk point (rounded kerb returns cut the corner)
    for (let d = 2.2; d <= 3.6 && !ok; d += 0.2) {
      const x = n.x + sx * ((n.hw || 11) + d), z = n.z + sz * ((n.hz || 5) + d * 0.9);
      if (isWalk(x, z) && inR(x, z, -WM)) ok = [x, z];
    }
    if (ok) { corners.set(cornerKey(n, sx, sz), P.length); P.push(ok); }
  }
}
const corner = (n, sx, sz) => corners.get(cornerKey(n, sx, sz));
const E = []; const seen = new Set();
const addEdge = (a, b, kind, axis, roadSide) => {
  if (a == null || b == null || a === b) return;
  const key = a < b ? a + ',' + b : b + ',' + a; if (seen.has(key)) return;
  const A = P[a], B = P[b], len = Math.hypot(B[0] - A[0], B[1] - A[1]);
  // validate the whole edge against the layout
  const n = Math.max(2, Math.ceil(len / 1.5));
  for (let i = 1; i < n; i++) {
    const x = A[0] + (B[0] - A[0]) * i / n, z = A[1] + (B[1] - A[1]) * i / n;
    if (kind === 0 ? !isWalk(x, z) : !isRoad(x, z)) return;
  }
  // side: +1 if the roadway lies to the RIGHT of A -> B (right = (-uz, ux) in the browser x, z frame), -1 if to the left; 0 for crosswalks
  let side = 0;
  if (roadSide) { const ux = (B[0] - A[0]) / len, uz = (B[1] - A[1]) / len; side = Math.sign((-uz) * roadSide[0] + ux * roadSide[1]) || 1; }
  seen.add(key); E.push({ a, b, kind, axis, len, side });
};
const at = new Map(nodes.map((n) => [n.j * R.nx + n.i, n]));
for (const n of nodes) {
  // along the avenue: south corners of (i, j) -> north corners of (i, j + 1)
  const m = at.get((n.j + 1) * R.nx + n.i);
  if (m && R.avSeg(n.i, n.j)) for (const sx of [-1, 1]) addEdge(corner(n, sx, 1), corner(m, sx, -1), 0, 0, [-sx, 0]);
  // along the street: east corners of (i, j) -> west corners of (i + 1, j)
  const q = at.get(n.j * R.nx + n.i + 1);
  if (q && R.stSeg(n.i, n.j)) for (const sz of [-1, 1]) addEdge(corner(n, 1, sz), corner(q, -1, sz), 0, 1, [0, -sz]);
  // crosswalks (only across existing legs)
  const leg = { N: n.j > 0 && R.avSeg(n.i, n.j - 1), S: R.avSeg(n.i, n.j), W: n.i > 0 && R.stSeg(n.i - 1, n.j), E: R.stSeg(n.i, n.j) };
  if (leg.N) addEdge(corner(n, -1, -1), corner(n, 1, -1), 1, 0);
  if (leg.S) addEdge(corner(n, -1, 1), corner(n, 1, 1), 1, 0);
  if (leg.W) addEdge(corner(n, -1, -1), corner(n, -1, 1), 1, 1);
  if (leg.E) addEdge(corner(n, 1, -1), corner(n, 1, 1), 1, 1);
}
// drop corners without edges, renumber
const used = new Set(); for (const e of E) { used.add(e.a); used.add(e.b); }
const remap = new Map(); const wl = ['# P6 city life pedestrian graph: generated by tools/life/export_lanes.mjs (do not edit)', `B ${rx0} ${rz0} ${rx1} ${rz1}`];
[...used].sort((a, b) => a - b).forEach((k, i) => { remap.set(k, i); wl.push(`P ${i} ${f(P[k][0])} ${f(P[k][1])}`); });
E.forEach((e, i) => wl.push(`E ${i} ${remap.get(e.a)} ${remap.get(e.b)} ${e.kind} ${e.axis} ${f(e.len)} ${e.side}`));
fs.writeFileSync(path.join(OUT, 'walk.txt'), wl.join('\n') + '\n');
console.log(`walk.txt: ${remap.size} corners, ${E.length} edges (${E.filter((e) => e.kind).length} crosswalks), sidewalk length ${f(E.filter((e) => !e.kind).reduce((s, e) => s + e.len, 0), 0)} m`);
