# Homage fan game tooling (not affiliated with Marvel/Sony/Insomniac). P6 city life.
# P1's signal props (mast arm + pole heads, post heads) -> unreal/WebHomage/Scripts/life_data/signals.txt : `M|P x z ry` (browser metres, three.js yaw).
# The lens overlay of AWHLifeTraffic draws lit lenses on them (the exported props carry only a static aState snapshot).
#   python3 tools/life/export_signals.py [layout.json]      (default: the export the P6 build uses, _scratch/life/manhattan/export/midtown3x3)
import json, os, sys
HERE = os.path.dirname(os.path.abspath(__file__)); WT = os.path.dirname(os.path.dirname(HERE))
lay = sys.argv[1] if len(sys.argv) > 1 else os.environ.get('SM2_LIFE_EXPORT', '/Users/midir/sm2-n1/_scratch/life/manhattan/export/midtown3x3') + '/layout.json'
L = json.load(open(lay))['instances']
out = ['# P6 city life signals: generated by tools/life/export_signals.py from the P1 layout.json (do not edit)  columns: M mast | P post, x, z (browser m), yaw ry (rad)']
n = {'M': 0, 'P': 0}
for pool, tag in (('mast', 'M'), ('post', 'P')):
    for it in (L.get(pool) or {}).get('items') or []:
        out.append('%s %.3f %.3f %.4f' % (tag, it['x'], it['z'], it['ry'])); n[tag] += 1
dst = os.path.join(WT, 'unreal/WebHomage/Scripts/life_data/signals.txt')
open(dst, 'w').write('\n'.join(out) + '\n')
print('signals: %d masts, %d posts -> %s' % (n['M'], n['P'], dst))
