#!/usr/bin/env python3
"""Terrain prep (piece E, CPU only): turns the terrain export (tools/export/export_terrain.mjs) into the derived inputs of unreal/WebHomage/Scripts/build_terrain.py.
  <scratch>/prep/pathmask.png    park path mask, 0.5 m texels over the park rectangle: R = edge distance e*2 (0 at the ribbon edge .. 1 at the centre line), G = inside any path
  <scratch>/prep/tuft.glb        one grass clump (9 curved blades, unit height; vertex colour R = height along the blade for the wind weight)
  <scratch>/prep/tufts.bin       float32 records [x, z, yaw, widthScale, heightMetres] (browser frame) scattered over the grass mask (parkmask.rgba)
  <scratch>/prep/stats.json      areas for the checkers (park land, grass-covered land, path / water / rock shares)
  unreal/WebHomage/Shaders/Terrain/ParkData.ush   meadow + pond constants of the park shader (gitignored: regenerated from the export on every build)
usage: prep_terrain.py [export_dir] [prep_dir]"""
import os, sys, json, math
import numpy as np
from PIL import Image
HERE = os.path.dirname(os.path.abspath(__file__)); REPO = os.path.abspath(os.path.join(HERE, '..', '..'))
sys.path.insert(0, os.path.join(REPO, 'tools', 'export'))
from glbio import read_glb, write_glb
SCR = os.environ.get('SM2_TERRAIN_SCRATCH', '/Users/midir/sm2-n1/_scratch/terrain')
EXP = sys.argv[1] if len(sys.argv) > 1 else os.environ.get('SM2_TERRAIN_EXPORT', os.path.join(SCR, 'export'))
PREP = sys.argv[2] if len(sys.argv) > 2 else os.path.join(SCR, 'prep')
os.makedirs(PREP, exist_ok=True)
T = json.load(open(os.path.join(EXP, 'terrain.json')))
PARK = T['G']['PARK']

# ------------------------------------------------------------------ ParkData.ush
def f4(*v): return 'float4(%s)' % ','.join('%.6ff' % x for x in v)
md = T['meadows']; pw = T['water']
ush = '''// GENERATED by tools/terrain/prep_terrain.py from the terrain export (terrain.json) -- do not edit, do not commit.
// Fan homage project; not an official Marvel / Sony / Insomniac product, no affiliation.
#pragma once
static const float4 uMd[%d] = { %s };
static const float uMa[%d] = { %s };
static const float4 uPw[%d] = { %s };
static const float uPa[%d] = { %s };
static const float4 uPh[%d] = { %s };
static const float uPq[%d] = { %s };
''' % (len(md), ', '.join(f4(m['x'], m['z'], m['rx'], m['rz']) for m in md), len(md), ', '.join('%.6ff' % m['a'] for m in md),
       len(pw), ', '.join(f4(w['cx'], w['cz'], w['rx'], w['rz']) for w in pw), len(pw), ', '.join('%.6ff' % w['a'] for w in pw),
       len(pw), ', '.join(f4(*w['h']) for w in pw), len(pw), ', '.join('%.6ff' % w['q'] for w in pw))
SH = os.path.join(REPO, 'unreal', 'WebHomage', 'Shaders', 'Terrain'); os.makedirs(SH, exist_ok=True)
open(os.path.join(SH, 'ParkData.ush'), 'w').write(ush)
print('ParkData.ush: %d meadows, %d ponds' % (len(md), len(pw)))

# ------------------------------------------------------------------ leaf textures (ez-tree leaf sprays) under the names the UE build expects
import shutil
for n in ('oak', 'ash', 'aspen', 'pine'): shutil.copyfile(os.path.join(REPO, 'public', 'assets', 'eztree', 'leaves', n + '.png'), os.path.join(PREP, 'leaf_' + n + '.png'))

# ------------------------------------------------------------------ path mask
TEXEL = 0.5
PX0, PZ0 = T['mask']['x0'], T['mask']['z0']                    # the grass mask rectangle (park + 2 m margin), 1 m texels
PW, PH = T['mask']['w'], T['mask']['h']
MW, MH = int(PW / TEXEL), int(PH / TEXEL)
g = read_glb(os.path.join(EXP, 'mesh', 'ground', 'parkPaths.glb'))
P = g['attrs']['POSITION']; UV = g['attrs']['TEXCOORD_0']; I = g['index'].reshape(-1, 3)
E = np.zeros((MH, MW), np.float32); COV = np.zeros((MH, MW), np.uint8)
for a, b, c in I:
    pa, pb, pc = P[a], P[b], P[c]
    xs = np.array([pa[0], pb[0], pc[0]]); zs = np.array([pa[2], pb[2], pc[2]])
    i0, i1 = int(math.floor((xs.min() - PX0) / TEXEL)), int(math.ceil((xs.max() - PX0) / TEXEL))
    j0, j1 = int(math.floor((zs.min() - PZ0) / TEXEL)), int(math.ceil((zs.max() - PZ0) / TEXEL))
    i0, j0, i1, j1 = max(i0, 0), max(j0, 0), min(i1, MW - 1), min(j1, MH - 1)
    if i1 < i0 or j1 < j0: continue
    ii, jj = np.meshgrid(np.arange(i0, i1 + 1), np.arange(j0, j1 + 1))
    x = PX0 + (ii + 0.5) * TEXEL; z = PZ0 + (jj + 0.5) * TEXEL
    d = (pb[2] - pc[2]) * (pa[0] - pc[0]) + (pc[0] - pb[0]) * (pa[2] - pc[2])
    if abs(d) < 1e-9: continue
    l1 = ((pb[2] - pc[2]) * (x - pc[0]) + (pc[0] - pb[0]) * (z - pc[2])) / d
    l2 = ((pc[2] - pa[2]) * (x - pc[0]) + (pa[0] - pc[0]) * (z - pc[2])) / d
    l3 = 1 - l1 - l2
    inside = (l1 >= -0.02) & (l2 >= -0.02) & (l3 >= -0.02)   # a hair of slack: hairline cracks between neighbouring ribbon quads
    u = l1 * UV[a][0] + l2 * UV[b][0] + l3 * UV[c][0]
    e = np.minimum(u, 1 - u)
    sub = E[j0:j1 + 1, i0:i1 + 1]; sub[inside] = np.maximum(sub[inside], e[inside])
    COV[j0:j1 + 1, i0:i1 + 1][inside] = 255
# park drives (7.4 m wide dark asphalt ribbons, hard edged): coverage into channel B
gd = read_glb(os.path.join(EXP, 'mesh', 'ground', 'park_drives.glb'))
DRV = np.zeros((MH, MW), np.uint8)
Pd = gd['attrs']['POSITION']; Id = gd['index'].reshape(-1, 3)
for a, b, c in Id:
    pa, pb, pc = Pd[a], Pd[b], Pd[c]
    xs = np.array([pa[0], pb[0], pc[0]]); zs = np.array([pa[2], pb[2], pc[2]])
    i0, i1 = max(int(math.floor((xs.min() - PX0) / TEXEL)), 0), min(int(math.ceil((xs.max() - PX0) / TEXEL)), MW - 1)
    j0, j1 = max(int(math.floor((zs.min() - PZ0) / TEXEL)), 0), min(int(math.ceil((zs.max() - PZ0) / TEXEL)), MH - 1)
    if i1 < i0 or j1 < j0: continue
    ii, jj = np.meshgrid(np.arange(i0, i1 + 1), np.arange(j0, j1 + 1))
    x = PX0 + (ii + 0.5) * TEXEL; z = PZ0 + (jj + 0.5) * TEXEL
    d = (pb[2] - pc[2]) * (pa[0] - pc[0]) + (pc[0] - pb[0]) * (pa[2] - pc[2])
    if abs(d) < 1e-9: continue
    l1 = ((pb[2] - pc[2]) * (x - pc[0]) + (pc[0] - pb[0]) * (z - pc[2])) / d; l2 = ((pc[2] - pa[2]) * (x - pc[0]) + (pa[0] - pc[0]) * (z - pc[2])) / d; l3 = 1 - l1 - l2
    DRV[j0:j1 + 1, i0:i1 + 1][(l1 >= -0.02) & (l2 >= -0.02) & (l3 >= -0.02)] = 255
R = np.clip(E * 2.0, 0, 1) * 255
img = np.zeros((MH, MW, 4), np.uint8); img[..., 0] = R.astype(np.uint8); img[..., 1] = COV; img[..., 2] = DRV; img[..., 3] = 255
Image.fromarray(img, 'RGBA').save(os.path.join(PREP, 'pathmask.png'))
json.dump({'x0': PX0, 'z0': PZ0, 'w_m': PW, 'h_m': PH, 'texel': TEXEL, 'px': [MW, MH]}, open(os.path.join(PREP, 'pathmask.json'), 'w'))
print('pathmask.png %dx%d, covered %.1f %% of the rectangle' % (MW, MH, 100 * (COV > 0).mean()))

# ------------------------------------------------------------------ park rocks: the schist outcrops of the browser's park-setpieces mesh (the Met-like museum triangles are dropped on purpose)
sp = os.path.join(EXP, 'mesh', 'setpieces', 'park_setpieces.glb')
if os.path.exists(sp):
    g = read_glb(sp); P3 = g['attrs']['POSITION']; N3 = g['attrs']['NORMAL']; I3 = g['index'].reshape(-1, 3)
    met = T['sites']['met']; c3 = P3[I3].mean(1); mg = 6.0
    keep_t = ~((c3[:, 0] > met['x0'] - mg) & (c3[:, 0] < met['x1'] + mg) & (c3[:, 2] > met['z0'] - mg) & (c3[:, 2] < met['z1'] + mg))
    I3 = I3[keep_t]; used = np.unique(I3.reshape(-1)); remap = -np.ones(len(P3), np.int64); remap[used] = np.arange(len(used))
    Pn = P3[used]; Nn = N3[used]; Ik = remap[I3].reshape(-1)
    h = np.abs(np.sin(np.floor(Pn[:, 0] / 1.6) * 12.9898 + np.floor(Pn[:, 2] / 1.6) * 78.233 + np.floor(Pn[:, 1] / 0.5) * 37.719) * 43758.5453) % 1.0
    base = np.array([0.46, 0.44, 0.40]); col = np.clip(base[None, :] * (0.72 + 0.5 * h)[:, None] * (0.85 + 0.25 * np.clip((Pn[:, 1] + 0.9) / 3.0, 0, 1))[:, None], 0, 1)
    write_glb(os.path.join(PREP, 'park_rocks.glb'), {'POSITION': Pn.astype(np.float32), 'NORMAL': Nn.astype(np.float32), 'TEXCOORD_0': np.zeros((len(Pn), 2), np.float32), 'COLOR_0': np.concatenate([col, np.ones((len(col), 1))], 1).astype(np.float32)}, Ik, 'park_rocks')
    print('park_rocks.glb: %d tris (museum dropped: %d)' % (len(Ik) // 3, int((~keep_t).sum())))

# ------------------------------------------------------------------ grass tuft prototype (unit height)
rng = np.random.default_rng(7)
PP, NN, UU, CC, II = [], [], [], [], []
blades, segs = 9, 3
for b in range(blades):
    a = rng.uniform(0, 2 * math.pi); r = 0.02 + rng.uniform(0, 0.12); lean = 0.10 + rng.uniform(0, 0.22); ha = rng.uniform(0, 2 * math.pi)
    ox, oz = math.cos(a) * r, math.sin(a) * r; w = 0.012 + rng.uniform(0, 0.008); hk = 0.65 + rng.uniform(0, 0.4)
    dx, dz = math.cos(ha), math.sin(ha); px, pz = -dz, dx
    v0 = len(PP)
    for s in range(segs + 1):
        t = s / segs; y = t * hk; bend = lean * t * t; ww = w * (1 - t * 0.85)
        for side in (-1, 1):
            PP.append((ox + dx * bend + px * ww * side, y, oz + dz * bend + pz * ww * side)); NN.append((dx * 0.3, 1.0, dz * 0.3)); UU.append((0.5 + 0.5 * side, t)); CC.append((t, t, t, 1.0))
    for s in range(segs):
        k = v0 + s * 2; II += [k, k + 1, k + 3, k, k + 3, k + 2]
PPa = np.array(PP, np.float32); NNa = np.array(NN, np.float32); NNa /= np.linalg.norm(NNa, axis=1, keepdims=True)
write_glb(os.path.join(PREP, 'tuft.glb'), {'POSITION': PPa, 'NORMAL': NNa, 'TEXCOORD_0': np.array(UU, np.float32), 'COLOR_0': np.array(CC, np.float32)}, np.array(II), 'tuft')
print('tuft.glb: %d blades, %d verts' % (blades, len(PP)))

# ------------------------------------------------------------------ tuft scatter over the grass mask (browser frame x, z)
M = np.fromfile(os.path.join(EXP, T['mask']['file']), np.uint8).reshape(PH, PW, 4)
dens = M[..., 0] / 255.0; hgt = M[..., 1] / 255.0
PER_M2 = float(os.environ.get('SM2_TUFT_PER_M2', '0.55'))
cell = 1.0 / math.sqrt(PER_M2)
nx, nz = int((PARK['x1'] - PARK['x0']) / cell), int((PARK['z1'] - PARK['z0']) / cell)
gi, gj = np.meshgrid(np.arange(nx), np.arange(nz))
jit = rng.uniform(0, 1, (nz, nx, 4))
x = PARK['x0'] + (gi + jit[..., 0]) * cell; z = PARK['z0'] + (gj + jit[..., 1]) * cell
mi = np.clip(np.floor(x - PX0).astype(int), 0, PW - 1); mj = np.clip(np.floor(z - PZ0).astype(int), 0, PH - 1)
keep = jit[..., 2] < dens[mj, mi]
# the path mask clears the path ribbons (with a soft margin) so no tuft grows through the gravel
pi_ = np.clip(np.floor((x - PX0) / TEXEL).astype(int), 0, MW - 1); pj_ = np.clip(np.floor((z - PZ0) / TEXEL).astype(int), 0, MH - 1)
keep &= (COV[pj_, pi_] == 0) & (DRV[pj_, pi_] == 0)
h = (0.06 + 0.4 * hgt[mj, mi]) * (0.7 + 0.6 * jit[..., 3])                  # grass.js blade height (m) x clump height (unit tuft is ~0.85 m high)
rec = np.stack([x[keep], z[keep], rng.uniform(0, 2 * math.pi, keep.sum()), rng.uniform(0.8, 1.35, keep.sum()), h[keep]], 1).astype(np.float32)
rec.tofile(os.path.join(PREP, 'tufts.bin'))
print('tufts: %d instances (%.2f / m2 target), %.1f %% of cells kept' % (len(rec), PER_M2, 100 * keep.mean()))

# ------------------------------------------------------------------ stats for the checkers (0.5 m grid over the mask rectangle)
from PIL import ImageDraw
def poly_area(pts): n = len(pts); return abs(sum(pts[i][0] * pts[(i + 1) % n][1] - pts[(i + 1) % n][0] * pts[i][1] for i in range(n))) / 2
water_m2 = sum(poly_area(w['pts']) for w in pw)
wimg = Image.new('L', (MW, MH), 0); dr = ImageDraw.Draw(wimg)
for w in pw: dr.polygon([((x - PX0) / TEXEL, (z - PZ0) / TEXEL) for x, z in w['pts']], fill=255)
WAT = np.array(wimg) > 0
xx = PX0 + (np.arange(MW)[None, :] + 0.5) * TEXEL + 0 * np.arange(MH)[:, None]; zz = PZ0 + (np.arange(MH)[:, None] + 0.5) * TEXEL + 0 * np.arange(MW)[None, :]
rect = (xx > PARK['x0']) & (xx < PARK['x1']) & (zz > PARK['z0']) & (zz < PARK['z1'])
met = T['sites']['met']; MET = (xx > met['x0']) & (xx < met['x1']) & (zz > met['z0']) & (zz < met['z1'])
PATH = (COV > 0) | (DRV > 0)
mi2 = np.clip(np.floor(xx - PX0).astype(int), 0, PW - 1); mj2 = np.clip(np.floor(zz - PZ0).astype(int), 0, PH - 1)
GRASS = dens[mj2, mi2] > 0
land = rect & ~WAT; open_land = land & ~PATH & ~MET
px = TEXEL * TEXEL
st = {'park_rect_m2': float(rect.sum() * px), 'water_m2': water_m2, 'park_land_m2': float(land.sum() * px), 'path_and_drive_m2': float((land & PATH).sum() * px), 'met_lot_m2': float((land & MET).sum() * px),
      'open_land_m2': float(open_land.sum() * px), 'grass_mask_on_open_land_m2': float((open_land & GRASS).sum() * px),
      'grass_cover_of_open_land_pct': 100 * float((open_land & GRASS).sum()) / float(open_land.sum()),
      'grass_cover_of_all_park_land_pct': 100 * float((land & GRASS & ~PATH).sum()) / float(land.sum()), 'tufts': int(len(rec))}
json.dump(st, open(os.path.join(PREP, 'stats.json'), 'w'), indent=1)
print(json.dumps(st, indent=1))
