; Homage fan game. Not an official Marvel, Sony or Insomniac game; no affiliation.
[/Script/UnrealEd.EditorProjectAppearanceSettings]
bDisplayUnits=True
bDisplayUnitsOnComponentTransforms=True
UnitDisplay=Metric
+DistanceUnits=Centimeters

[/Script/PythonScriptPlugin.PythonScriptPluginSettings]
bIsolateInterpreterEnvironment=True
