# Homage fan game. Not an official Marvel, Sony or Insomniac game; no affiliation.
# P1 City: idempotent rebuild of /Game/City and /Game/Tests/City from committed sources.
#   sources: browser city export (tools/export/export_city.mjs -> <EXPORT>/manifest.json, mesh/, proto/, layout.json)
#            textures prepared by tools/export/prep_textures.py (<TEX>), shader includes Shaders/City/*.ush
#            (generated by tools/export/gen_shaders.mjs from src/world/*.js)
#   run: tools/export/build_city.sh (export + prep + this script in the P1 editor or headless -run=pythonscript)
# Frame: browser metres (x east, y up, z south) -> UE cm: X = 100 x, Y = 100 z, Z = 100 y (north = -Y).
import unreal, os, json, math, time

EXPORT = os.environ.get('SM2_CITY_EXPORT', '/Users/midir/sm2-n1/_scratch/city/export/midtown3x3')
TEX = os.environ.get('SM2_CITY_TEX', '/Users/midir/sm2-n1/_scratch/city/tex')
try: ARGS = JOB_ARGS  # noqa: F821 (set by tools/export/ue/uejob.py)
except NameError: ARGS = {}
STEPS = set((ARGS.get('steps') or 'clean,tex,mat,mesh,proto,map').split(','))
ROOT, TESTS = '/Game/City', '/Game/Tests/City'
at = unreal.AssetToolsHelpers.get_asset_tools()
EAL = unreal.EditorAssetLibrary
mel = unreal.MaterialEditingLibrary
T0 = time.time()
def log(*a): print('[build_city %5.0fs]' % (time.time() - T0), *a)

# ------------------------------------------------------------------------------------------------ helpers
def import_files(files, dest, pipeline=None):
    tasks = []
    for f in files:
        t = unreal.AssetImportTask(); t.filename = f; t.destination_path = dest; t.automated = True; t.replace_existing = True; t.save = False
        if pipeline: t.options = pipeline
        tasks.append(t)
    at.import_asset_tasks(tasks)
    return tasks

def tex_settings(t, srgb, comp=unreal.TextureCompressionSettings.TC_BC7, wrap=True):
    t.set_editor_property('srgb', srgb)
    t.set_editor_property('compression_settings', comp)
    if not wrap:
        t.set_editor_property('address_x', unreal.TextureAddress.TA_CLAMP); t.set_editor_property('address_y', unreal.TextureAddress.TA_CLAMP)

def load(p): return unreal.load_asset(p)

# ------------------------------------------------------------------------------------------------ clean
if 'clean' in STEPS:
    unreal.EditorLoadingAndSavingUtils.new_blank_map(False)
    for d in (ROOT,):  # test maps are reused / emptied by the map step (deleting maps pops a modal dialog)
        if EAL.does_directory_exist(d): EAL.delete_directory(d)
    log('cleaned')

# ------------------------------------------------------------------------------------------------ textures
PLAIN_SRGB = {'interiors': True, 'signs': True, 'noise': False, 'detail_nrm': False, 'asphalt_col': True, 'asphalt_nrm': False, 'asphalt_macro': False,
              'asphalt_decals': False, 'sidewalk_col': True, 'sidewalk_nrm': False, 'curb_col': True, 'markings': True, 'leaves': True}
ARRAYS = {'walls_col': (16, True), 'walls_nrm': (16, False), 'walls_hao': (17, False), 'roof_col': (19, True), 'roof_nrm': (19, False)}
if 'tex' in STEPS:
    import_files([os.path.join(TEX, k + '.png') for k in PLAIN_SRGB], ROOT + '/Textures')
    for k, s in PLAIN_SRGB.items():
        t = load(f'{ROOT}/Textures/{k}')
        tex_settings(t, s, unreal.TextureCompressionSettings.TC_VECTOR_DISPLACEMENTMAP if k == 'noise' else unreal.TextureCompressionSettings.TC_BC7,
                     wrap=k not in ('interiors', 'signs', 'markings', 'leaves'))
    maps = sorted(f for f in os.listdir(os.path.join(TEX, 'maps')) if f.endswith('.png'))
    import_files([os.path.join(TEX, 'maps', f) for f in maps], ROOT + '/Textures/Maps')
    for f in maps:
        t = load(f'{ROOT}/Textures/Maps/{f[:-4]}'); tex_settings(t, 'noise' not in f)
    for name, (n, srgb) in ARRAYS.items():
        files = [os.path.join(TEX, f'{name}_L{k:02d}.png') for k in range(n)]
        import_files(files, ROOT + '/Textures/Layers')
        layers = []
        for k in range(n):
            t = load(f'{ROOT}/Textures/Layers/{name}_L{k:02d}'); tex_settings(t, srgb); layers.append(t)
        arr = load(f'{ROOT}/Textures/TA_{name}') if EAL.does_asset_exist(f'{ROOT}/Textures/TA_{name}') else at.create_asset('TA_' + name, ROOT + '/Textures', unreal.Texture2DArray, unreal.Texture2DArrayFactory())
        arr.set_editor_property('source_textures', layers)  # PostEditChange rebuilds the array source from the layers
        tex_settings(arr, srgb)
        arr.set_editor_property('address_x', unreal.TextureAddress.TA_WRAP); arr.set_editor_property('address_y', unreal.TextureAddress.TA_WRAP)
    EAL.save_directory(ROOT + '/Textures', only_if_is_dirty=False, recursive=True)
    log('textures done')

# ------------------------------------------------------------------------------------------------ materials
MAT = ROOT + '/Materials'
def sampler_for(t):
    if isinstance(t, unreal.Texture2DArray) or True:
        return unreal.MaterialSamplerType.SAMPLERTYPE_COLOR if t.get_editor_property('srgb') else unreal.MaterialSamplerType.SAMPLERTYPE_LINEAR_COLOR

def make_material(name, include, code, inputs, outputs, blend='opaque', two_sided=False, world_normal=True, domain_hint=None, scalar_defaults=None):
    """inputs: list of (name, kind, arg): kind in tex|uv|vc|wpos|wn|cam|scalar|mpc|pcd.  outputs: list of (name, n, property)."""
    path = f'{MAT}/{name}'
    if EAL.does_asset_exist(path):  # reuse (deleting a referenced material pops a dialog): clear its graph
        m = load(path); mel.delete_all_material_expressions(m)
    else:
        m = at.create_asset(name, MAT, unreal.Material, unreal.MaterialFactoryNew())
    m.set_editor_property('tangent_space_normal', not world_normal)
    if blend == 'masked': m.set_editor_property('blend_mode', unreal.BlendMode.BLEND_MASKED)
    m.set_editor_property('two_sided', two_sided)
    c = mel.create_material_expression(m, unreal.MaterialExpressionCustom, -400, 0)
    c.set_editor_property('code', code)
    c.set_editor_property('output_type', unreal.CustomMaterialOutputType.CMOT_FLOAT3)
    c.set_editor_property('description', name)
    if include: c.set_editor_property('include_file_paths', [include])
    ins = []
    for n, kind, arg in inputs:
        ci = unreal.CustomInput(); ci.set_editor_property('input_name', n); ins.append(ci)
    c.set_editor_property('inputs', ins)
    outs = []
    for n, k, _ in outputs[1:]:
        co = unreal.CustomOutput(); co.set_editor_property('output_name', n)
        co.set_editor_property('output_type', [None, unreal.CustomMaterialOutputType.CMOT_FLOAT1, unreal.CustomMaterialOutputType.CMOT_FLOAT2, unreal.CustomMaterialOutputType.CMOT_FLOAT3][k])
        outs.append(co)
    c.set_editor_property('additional_outputs', outs)
    y = -1200
    for n, kind, arg in inputs:
        y += 90
        if kind == 'tex':
            e = mel.create_material_expression(m, unreal.MaterialExpressionTextureObject, -900, y)
            t = load(arg); e.set_editor_property('texture', t); e.set_editor_property('sampler_type', sampler_for(t))
        elif kind == 'texparam':
            e = mel.create_material_expression(m, unreal.MaterialExpressionTextureObjectParameter, -900, y)
            e.set_editor_property('parameter_name', n); t = load(arg); e.set_editor_property('texture', t); e.set_editor_property('sampler_type', sampler_for(t))
        elif kind == 'uv':
            e = mel.create_material_expression(m, unreal.MaterialExpressionTextureCoordinate, -900, y); e.set_editor_property('coordinate_index', arg)
        elif kind == 'vc':
            e = mel.create_material_expression(m, unreal.MaterialExpressionVertexColor, -900, y)
        elif kind == 'wpos':
            e = mel.create_material_expression(m, unreal.MaterialExpressionWorldPosition, -900, y)
        elif kind == 'wn':
            e = mel.create_material_expression(m, unreal.MaterialExpressionVertexNormalWS, -900, y)
        elif kind == 'cam':
            e = mel.create_material_expression(m, unreal.MaterialExpressionCameraPositionWS, -900, y)
        elif kind == 'scalar':
            e = mel.create_material_expression(m, unreal.MaterialExpressionScalarParameter, -900, y)
            e.set_editor_property('parameter_name', n); e.set_editor_property('default_value', arg)
        elif kind == 'vector':
            e = mel.create_material_expression(m, unreal.MaterialExpressionVectorParameter, -900, y)
            e.set_editor_property('parameter_name', n); e.set_editor_property('default_value', unreal.LinearColor(*arg))
        elif kind == 'mpc':
            e = mel.create_material_expression(m, unreal.MaterialExpressionCollectionParameter, -900, y)
            e.set_editor_property('collection', load(MAT + '/MPC_City')); e.set_editor_property('parameter_name', arg)
        elif kind == 'pcd':
            e = mel.create_material_expression(m, unreal.MaterialExpressionPerInstanceCustomData, -900, y)
            e.set_editor_property('data_index', arg[0])
        mel.connect_material_expressions(e, '', c, n)
    for i, (n, k, prop) in enumerate(outputs):
        if prop is None: continue
        mel.connect_material_property(c, '' if i == 0 else n, prop)
    mel.recompile_material(m)
    EAL.save_asset(path)
    return m

MP = unreal.MaterialProperty
TEXA = lambda n: f'{ROOT}/Textures/{n}'
WORLD = [('wpos', 'wpos', None), ('wn', 'wn', None), ('cam', 'cam', None)]

if 'mat' in STEPS:
    # the editor caches shader source files: reload the regenerated /Project/City/*.ush includes
    unreal.SystemLibrary.execute_console_command(None, 'recompileshaders changed')
    if not EAL.does_asset_exist(MAT + '/MPC_City'):
        mpc = at.create_asset('MPC_City', MAT, unreal.MaterialParameterCollection, unreal.MaterialParameterCollectionFactoryNew())
        sp = []
        for n, v in (('NightK', 0.0), ('DnTime', 0.0), ('InteriorGain', 0.5), ('ShopGain', 0.7), ('EmissiveScale', 3.0)):
            p = unreal.CollectionScalarParameter(); p.set_editor_property('parameter_name', n); p.set_editor_property('default_value', v); sp.append(p)
        mpc.set_editor_property('scalar_parameters', sp); EAL.save_asset(MAT + '/MPC_City')
    # facade (facade.js FRAG_DECL port)
    make_material('M_CityFacade', '/Project/City/Facade.ush', '''
float r, m, g; float3 n, e, f;
float3 a = CityFacade(tWallC, tWallCSampler, tWallN, tWallNSampler, tWallH, tWallHSampler, tDetail, tDetailSampler, tInterior, tInteriorSampler, tSigns, tSignsSampler, tNoise, tNoiseSampler,
  uv0, float4(uv1, uv2), float4(uv3, uv4), float4(uv5, uv6), uv7, vc.rgb * 2.0, wpos, wn, cam, float4(igain, sgain, nightk, dntime), float2(0.0, 0.0), r, m, n, e, g, f);
// coated curtain glass (F0 0.2-0.6): metallic mirror = F0 x tint. Old sash glass (gSash): dielectric with F0 = 0.011 so
// that UE's F90 = saturate(50 F0) = 0.55 matches the browser's specularF90 0.55 (no bright grazing mirrors on masonry)
float gm = g * (1.0 - gSash);
Rough = r; Metal = lerp(m, 1.0, gm); NormalW = n; Emis = e * escale; Spec = lerp(0.5, 0.1375, g * gSash);
return lerp(a, f, gm);''',
        [('tWallC', 'tex', TEXA('TA_walls_col')), ('tWallN', 'tex', TEXA('TA_walls_nrm')), ('tWallH', 'tex', TEXA('TA_walls_hao')), ('tDetail', 'tex', TEXA('detail_nrm')),
         ('tInterior', 'tex', TEXA('interiors')), ('tSigns', 'tex', TEXA('signs')), ('tNoise', 'tex', TEXA('noise'))]
        + [(f'uv{i}', 'uv', i) for i in range(8)] + [('vc', 'vc', None)] + WORLD
        + [('igain', 'mpc', 'InteriorGain'), ('sgain', 'mpc', 'ShopGain'), ('nightk', 'mpc', 'NightK'), ('dntime', 'mpc', 'DnTime'), ('escale', 'mpc', 'EmissiveScale')],
        [('', 3, MP.MP_BASE_COLOR), ('Rough', 1, MP.MP_ROUGHNESS), ('Metal', 1, MP.MP_METALLIC), ('NormalW', 3, MP.MP_NORMAL), ('Emis', 3, MP.MP_EMISSIVE_COLOR), ('Spec', 1, MP.MP_SPECULAR)])
    make_material('M_CityDetail', '/Project/City/Detail.ush', '''
float r, m, o; float3 n;
float3 a = CityDetail(tNoise, tNoiseSampler, tDetail, tDetailSampler, vc.rgb, uv1.x, uv0, wpos, wn, cam, Parameters.SvPosition.xy, r, m, n, o);
Rough = r; Metal = m; NormalW = n; Op = o; return a;''',
        [('tNoise', 'tex', TEXA('noise')), ('tDetail', 'tex', TEXA('detail_nrm')), ('uv0', 'uv', 0), ('uv1', 'uv', 1), ('vc', 'vc', None)] + WORLD,
        [('', 3, MP.MP_BASE_COLOR), ('Rough', 1, MP.MP_ROUGHNESS), ('Metal', 1, MP.MP_METALLIC), ('NormalW', 3, MP.MP_NORMAL), ('Op', 1, MP.MP_OPACITY_MASK)], blend='masked')
    make_material('M_CityRoof', '/Project/City/Roof.ush', '''
float r, m; float3 n;
float3 a = CityRoof(tRoofC, tRoofCSampler, tRoofN, tRoofNSampler, tNoiseR, tNoiseRSampler, vc.rgb, uv0, float4(uv1, uv2), float4(uv3, uv4), wpos, wn, cam, r, m, n);
Rough = r; Metal = m; NormalW = n; return a;''',
        [('tRoofC', 'tex', TEXA('TA_roof_col')), ('tRoofN', 'tex', TEXA('TA_roof_nrm')), ('tNoiseR', 'tex', TEXA('noise'))] + [(f'uv{i}', 'uv', i) for i in range(5)] + [('vc', 'vc', None)] + WORLD,
        [('', 3, MP.MP_BASE_COLOR), ('Rough', 1, MP.MP_ROUGHNESS), ('Metal', 1, MP.MP_METALLIC), ('NormalW', 3, MP.MP_NORMAL)])
    make_material('M_CityAsphalt', '/Project/City/Asphalt.ush', '''
float r; float3 n;
float3 a = CityAsphalt(tCol, tColSampler, tNrm, tNrmSampler, tMacro, tMacroSampler, tNoise, tNoiseSampler, tDec, tDecSampler, float3(uv0, uv1.x), wpos, cam, r, n);
Rough = r; NormalW = n; return a;''',
        [('tCol', 'tex', TEXA('asphalt_col')), ('tNrm', 'tex', TEXA('asphalt_nrm')), ('tMacro', 'tex', TEXA('asphalt_macro')), ('tNoise', 'tex', TEXA('noise')), ('tDec', 'tex', TEXA('asphalt_decals')),
         ('uv0', 'uv', 0), ('uv1', 'uv', 1), ('wpos', 'wpos', None), ('cam', 'cam', None)],
        [('', 3, MP.MP_BASE_COLOR), ('Rough', 1, MP.MP_ROUGHNESS), ('NormalW', 3, MP.MP_NORMAL)])
    make_material('M_CitySidewalk', '/Project/City/Sidewalk.ush', '''
float r; float3 n;
float3 a = CitySidewalk(tCol, tColSampler, tNrm, tNrmSampler, tNoise, tNoiseSampler, tCurb, tCurbSampler, float4(uv0, uv1), wpos, wn, cam, r, n);
Rough = r; NormalW = n; return a;''',
        [('tCol', 'tex', TEXA('sidewalk_col')), ('tNrm', 'tex', TEXA('sidewalk_nrm')), ('tNoise', 'tex', TEXA('noise')), ('tCurb', 'tex', TEXA('curb_col')), ('uv0', 'uv', 0), ('uv1', 'uv', 1)] + WORLD,
        [('', 3, MP.MP_BASE_COLOR), ('Rough', 1, MP.MP_ROUGHNESS), ('NormalW', 3, MP.MP_NORMAL)])
    # generic vertex-colour / atlas material (Times Square dressing, signage, markings): masked by the map alpha
    make_material('M_CityVC', None, '''
float4 t = UseMap > 0.5 ? Texture2DSample(Map, MapSampler, float2(uv0.x, 1.0 - uv0.y)) : float4(1, 1, 1, 1);
float3 c = vc.rgb * Tint.rgb * t.rgb;
Rough = RoughP; Metal = MetalP; Op = t.a > AlphaCut ? 1.0 : 0.0; Emis = c * EmisGain;
return c;''',
        [('Map', 'texparam', TEXA('markings')), ('UseMap', 'scalar', 0.0), ('uv0', 'uv', 0), ('vc', 'vc', None), ('Tint', 'vector', (1, 1, 1, 1)),
         ('RoughP', 'scalar', 0.7), ('MetalP', 'scalar', 0.0), ('EmisGain', 'scalar', 0.0), ('AlphaCut', 'scalar', 0.0)],
        [('', 3, MP.MP_BASE_COLOR), ('Rough', 1, MP.MP_ROUGHNESS), ('Metal', 1, MP.MP_METALLIC), ('Op', 1, MP.MP_OPACITY_MASK), ('Emis', 3, MP.MP_EMISSIVE_COLOR)],
        blend='masked', world_normal=False)
    # props (partmat.js port): per-part roughness / metal / emission, per-instance tint in custom data 0..2, state in 3
    make_material('M_CityProp', None, '''
float4 t = UseMap > 0.5 ? Texture2DSample(Map, MapSampler, float2(uv0.x, 1.0 - uv0.y)) : float4(1, 1, 1, 1);
float3 c = vc.rgb * t.rgb; int P = (int)(uv1.x + 0.5); float3 tint = (t0 + t1 + t2) > 0.0 ? float3(t0, t1, t2) : float3(1, 1, 1); float st = t3;
float pR = 0.7, pM = 0.0; float3 pE = 0;
if (P == 1) { c *= tint; pR = 0.32; } else if (P == 2) { pR = 0.28; pM = 1.0; } else if (P == 3) { c = float3(0.012, 0.014, 0.016); pR = 0.04; }
else if (P == 4) { pR = 0.2; pE = c * 0.4; } else if (P == 5) pR = 0.92; else if (P == 6) pR = 0.55; else if (P == 7) { pR = 0.08; pM = 0.6; pE = 0.12; }
else if (P == 8) { pR = 0.2; pE = c * (0.3 + st * 7.0); } else if (P == 9) pR = 0.85;
else if (P >= 10 && P <= 12) { float on = abs(float(P - 10) - st) < 0.5 ? 1.0 : 0.0; float3 lc = P == 10 ? float3(1, 0.06, 0.03) : (P == 11 ? float3(1, 0.5, 0.02) : float3(0.05, 1, 0.45)); c = lc * 0.05; pR = 0.15; pE = lc * on * 30.0; }
else if (P == 13) { float3 lc = st > 1.5 ? float3(0.9, 0.95, 1.0) : float3(1.0, 0.45, 0.05); c = lc * 0.05; pE = lc * 10.0; }
else if (P == 14) { pR = 0.1; pE = c * 3.0; } else if (P == 15) { pR = 0.3; pE = c * 0.25; } else if (P >= 16 && P <= 22) pR = 0.8;
if (nightk > 0.0) { if (P == 4) pE += float3(1.0, 0.78, 0.5) * 9.0 * nightk; else if (P == 7) pE += float3(1.0, 0.93, 0.8) * 7.0 * nightk; }
Rough = pR; Metal = pM; Emis = pE * escale;
return c;''',
        [('Map', 'texparam', TEXA('markings')), ('UseMap', 'scalar', 0.0), ('uv0', 'uv', 0), ('uv1', 'uv', 1), ('vc', 'vc', None),
         ('t0', 'pcd', (0, 1.0)), ('t1', 'pcd', (1, 1.0)), ('t2', 'pcd', (2, 1.0)), ('t3', 'pcd', (3, 0.0)), ('nightk', 'mpc', 'NightK'), ('escale', 'mpc', 'EmissiveScale')],
        [('', 3, MP.MP_BASE_COLOR), ('Rough', 1, MP.MP_ROUGHNESS), ('Metal', 1, MP.MP_METALLIC), ('Emis', 3, MP.MP_EMISSIVE_COLOR)], world_normal=False)
    # tree leaves: alpha-tested cards, two-sided, per-vertex / per-instance tint
    make_material('M_CityLeaves', None, '''
float4 t = Texture2DSample(Map, MapSampler, float2(uv0.x, 1.0 - uv0.y));
Op = t.a > 0.5 ? 1.0 : 0.0; Sub = t.rgb * float3(0.6, 0.8, 0.3);
return t.rgb * Tint.rgb;''',
        [('Map', 'texparam', TEXA('leaves')), ('uv0', 'uv', 0), ('Tint', 'vector', (0.85, 0.95, 0.7, 1))],
        [('', 3, MP.MP_BASE_COLOR), ('Op', 1, MP.MP_OPACITY_MASK), ('Sub', 3, None)], blend='masked', two_sided=True, world_normal=False)
    EAL.save_directory(MAT, only_if_is_dirty=False, recursive=True)
    log('materials done')

# ------------------------------------------------------------------------------------------------ meshes
man = json.load(open(os.path.join(EXPORT, 'manifest.json')))
KIND_MAT = {'facade': 'M_CityFacade', 'detail': 'M_CityDetail', 'roofs': 'M_CityRoof', 'asphalt': 'M_CityAsphalt', 'sidewalk': 'M_CitySidewalk'}
EMIS = ('tsScreens', 'tsTicker', 'tsNeon', 'tsLights', 'tsSigns', 'tsBands', 'signage', 'grandCentralGlow', 'parkPodiumGlow')
def mesh_pipeline(nanite):
    p = unreal.InterchangeGenericAssetsPipeline()
    p.common_meshes_properties.set_editor_properties({'recompute_normals': False, 'recompute_tangents': False, 'use_full_precision_u_vs': True,
        'remove_degenerates': False, 'vertex_color_import_option': unreal.InterchangeVertexColorImportOption.IVCIO_REPLACE})
    p.mesh_pipeline.set_editor_properties({'generate_lightmap_u_vs': False, 'build_nanite': nanite})
    p.material_pipeline.set_editor_property('import_materials', False)
    p.material_pipeline.texture_pipeline.set_editor_property('import_textures', False)
    return p
def mi_for(rec):
    """material instance of M_CityVC for a generic mesh (colour / roughness / map from the three.js material)"""
    mat = rec.get('mat') or {}
    key = rec['name']
    path = f'{MAT}/Inst/MI_{key}'
    if EAL.does_asset_exist(path): return load(path)
    mi = at.create_asset('MI_' + key, MAT + '/Inst', unreal.MaterialInstanceConstant, unreal.MaterialInstanceConstantFactoryNew())
    mel.set_material_instance_parent(mi, load(MAT + ('/M_CityProp' if rec.get('proto') and 'aPart.x' in rec.get('uv', []) else '/M_CityVC')))
    col = mat.get('color') or [1, 1, 1]
    if not rec.get('proto'):
        mel.set_material_instance_vector_parameter_value(mi, 'Tint', unreal.LinearColor(col[0], col[1], col[2], 1))
        mel.set_material_instance_scalar_parameter_value(mi, 'RoughP', float(mat.get('roughness') or 0.7))
        mel.set_material_instance_scalar_parameter_value(mi, 'MetalP', float(mat.get('metalness') or 0.0))
        if key.startswith(EMIS) or any(key.startswith(e) for e in EMIS): mel.set_material_instance_scalar_parameter_value(mi, 'EmisGain', 2.0)
        if mat.get('alphaTest') or key == 'markings': mel.set_material_instance_scalar_parameter_value(mi, 'AlphaCut', 0.5)
    u = mat.get('map')
    if u:
        rel = u.split('5202/', 1)[-1].split('?')[0].replace('/', '_').rsplit('.', 1)[0]
        tp = f'{ROOT}/Textures/Maps/{rel}'
        if EAL.does_asset_exist(tp):
            mel.set_material_instance_texture_parameter_value(mi, 'Map', load(tp)); mel.set_material_instance_scalar_parameter_value(mi, 'UseMap', 1.0)
    EAL.save_asset(path)
    return mi

def keep_mesh(rec):
    m = rec.get('mat') or {}
    if rec['kind'] in KIND_MAT or rec['name'] == 'markings': return True
    return not m.get('transparent')  # additive / multiply overlays (spill, halos, AO, grime) are left out for now

sms = ueditor = unreal.get_editor_subsystem(unreal.StaticMeshEditorSubsystem)
def finish_mesh(sm, mat, collide, nanite=False):
    sm.set_material(0, mat)
    ns = sm.get_editor_property('nanite_settings')  # Nanite quantises UVs: the facade / roof data channels need full precision
    if ns.enabled != nanite: ns.enabled = nanite; sm.set_editor_property('nanite_settings', ns)
    bs = sms.get_lod_build_settings(sm, 0)
    bs.set_editor_property('use_full_precision_u_vs', True); bs.set_editor_property('generate_lightmap_u_vs', False)
    bs.set_editor_property('recompute_normals', False); bs.set_editor_property('recompute_tangents', False)
    sms.set_lod_build_settings(sm, 0, bs)
    if collide:
        bsetup = sm.get_editor_property('body_setup')
        if bsetup: bsetup.set_editor_property('collision_trace_flag', unreal.CollisionTraceFlag.CTF_USE_COMPLEX_AS_SIMPLE)

if 'mesh' in STEPS:
    recs = [r for r in man['meshes'] if keep_mesh(r)]
    for nan in (False, True):
        group = [r for r in recs if (r['kind'] == 'detail') == nan]
        dest = ROOT + '/Meshes'
        import_files([os.path.join(EXPORT, r['file']) for r in group], dest + '/_in', mesh_pipeline(nan))
    n = 0
    for r in recs:
        base = os.path.basename(r['file'])[:-4]
        src = f'{ROOT}/Meshes/_in/{base}/StaticMeshes/{base}'
        dst = f'{ROOT}/Meshes/{r["kind"]}/SM_{base}'
        if not EAL.does_asset_exist(src): log('MISSING import', src); continue
        EAL.rename_asset(src, dst)
        sm = load(dst)
        mat = load(f'{MAT}/{KIND_MAT[r["kind"]]}') if r['kind'] in KIND_MAT else mi_for(r)
        finish_mesh(sm, mat, r['kind'] in ('facade', 'roofs', 'asphalt', 'sidewalk', 'detail') and not r.get('lod'), nanite=r['kind'] == 'detail')
        EAL.save_asset(dst); n += 1
    EAL.delete_directory(ROOT + '/Meshes/_in')
    log('meshes', n)

# ------------------------------------------------------------------------------------------------ prototypes (instanced props / trees)
SKIP_POOL = ('Far', '_mid', '_far', '_xfar', 'lampPool', 'propContactAO', 'trees_', 'trunks_', '_l1_', 'roofplants', 'hvac_', 'vents_', 'dish_', 'antenna_', 'flags')
protos = [p for p in man['protos'] if not any(s in p['name'] for s in SKIP_POOL)]
if 'proto' in STEPS:
    import_files([os.path.join(EXPORT, p['file']) for p in protos], ROOT + '/Props/_in', mesh_pipeline(True))
    for p in protos:
        src = f'{ROOT}/Props/_in/{p["name"]}/StaticMeshes/{p["name"]}'; dst = f'{ROOT}/Props/SM_{p["name"]}'
        if not EAL.does_asset_exist(src): log('MISSING proto', src); continue
        EAL.rename_asset(src, dst); sm = load(dst)
        if 'leaves' in p['name']:
            mi = at.create_asset('MI_' + p['name'], MAT + '/Inst', unreal.MaterialInstanceConstant, unreal.MaterialInstanceConstantFactoryNew())
            mel.set_material_instance_parent(mi, load(MAT + '/M_CityLeaves'))
            u = (p.get('mat') or {}).get('map')
            if u:
                rel = u.split('5202/', 1)[-1].replace('/', '_').rsplit('.', 1)[0]
                if EAL.does_asset_exist(f'{ROOT}/Textures/Maps/{rel}'): mel.set_material_instance_texture_parameter_value(mi, 'Map', load(f'{ROOT}/Textures/Maps/{rel}'))
            EAL.save_asset(mi.get_path_name())
        else:
            mi = mi_for({**p, 'proto': True})
        finish_mesh(sm, mi, False, nanite=True)
        EAL.save_asset(dst)
    EAL.delete_directory(ROOT + '/Props/_in')
    log('protos', len(protos))

# ------------------------------------------------------------------------------------------------ maps
def U(x, y, z): return unreal.Vector(x * 100.0, z * 100.0, y * 100.0)
def look_rot(p, t):
    d = unreal.Vector(t.x - p.x, t.y - p.y, t.z - p.z)
    yaw = math.degrees(math.atan2(d.y, d.x)); pitch = math.degrees(math.atan2(d.z, math.hypot(d.x, d.y)))
    return unreal.Rotator(roll=0.0, pitch=pitch, yaw=yaw)
eas = unreal.get_editor_subsystem(unreal.EditorActorSubsystem)
les = unreal.get_editor_subsystem(unreal.LevelEditorSubsystem)
def spawn(cls, loc=unreal.Vector(0, 0, 0), rot=unreal.Rotator(0, 0, 0), label=None, folder=None):
    a = eas.spawn_actor_from_class(cls, loc, rot)
    if label: a.set_actor_label(label)
    if folder: a.set_folder_path(folder)
    return a
sds = unreal.get_engine_subsystem(unreal.SubobjectDataSubsystem)
def add_component(actor, cls):
    root = sds.k2_gather_subobject_data_for_instance(actor)[0]
    h, fail = sds.add_new_subobject(unreal.AddNewSubobjectParams(parent_handle=root, new_class=cls, blueprint_context=None))
    return unreal.SubobjectDataBlueprintFunctionLibrary.get_object(unreal.SubobjectDataBlueprintFunctionLibrary.get_data(h))

SHOTS = json.load(open(os.path.join(os.path.dirname(os.path.abspath(__file__)) if '__file__' in globals() and os.path.exists(os.path.join(os.path.dirname(os.path.abspath(__file__)), 'city_shots.json')) else '/Users/midir/sm2-n1/city/unreal/WebHomage/Scripts', 'city_shots.json')))

def open_level(path):
    """idempotent: an existing map is opened and emptied (deleting maps pops a modal dialog), else created"""
    if EAL.does_asset_exist(path):
        unreal.EditorLoadingAndSavingUtils.load_map(path)
        for a in eas.get_all_level_actors():
            if a.get_class().get_name() not in ('WorldSettings', 'Brush', 'DefaultPhysicsVolume', 'GameplayDebuggerCategoryReplicator', 'WorldDataLayers', 'WorldPartitionMiniMap'):
                eas.destroy_actor(a)
    else:
        les.new_level(path)
    return unreal.get_editor_subsystem(unreal.UnrealEditorSubsystem).get_editor_world()

def build_geo_level(path):
    open_level(path)
    recs = [r for r in man['meshes'] if keep_mesh(r)]
    for r in recs:
        base = os.path.basename(r['file'])[:-4]; sp = f'{ROOT}/Meshes/{r["kind"]}/SM_{base}'
        if not EAL.does_asset_exist(sp): continue
        a = spawn(unreal.StaticMeshActor, U(r['center'][0], 0, r['center'][2]), label=base, folder='City/' + r['kind'])
        smc = a.static_mesh_component; smc.set_static_mesh(load(sp))
        a.set_mobility(unreal.ComponentMobility.STATIC)
    # instanced props / trees from layout.json pool items
    L = json.load(open(os.path.join(EXPORT, 'layout.json')))
    ni = 0
    for p in protos:
        pool = p['src']; items = (L['instances'].get(pool) or {}).get('items') or []
        sp = f'{ROOT}/Props/SM_{p["name"]}'
        if not items or not EAL.does_asset_exist(sp): continue
        a = spawn(unreal.Actor, unreal.Vector(0, 0, 0), label='ISM_' + p['name'], folder='City/Props')
        c = add_component(a, unreal.HierarchicalInstancedStaticMeshComponent)
        c.set_static_mesh(load(sp)); c.set_editor_property('num_custom_data_floats', 4)
        xs = []
        for it in items:
            s = it.get('s', 1.0); s3 = it.get('s3') or [1, 1, 1]
            # browser: rotation about +y by ry (right-handed, y up). UE: yaw about Z with Y = z mirrored handedness -> yaw = -ry
            rot = unreal.Rotator(roll=math.degrees(it.get('rz', 0.0)), pitch=-math.degrees(it.get('rx', 0.0)), yaw=-math.degrees(it.get('ry', 0.0)))
            xs.append(unreal.Transform(U(it['x'], it['y'], it['z']), rot, unreal.Vector(s * s3[0], s * s3[2], s * s3[1])))
        ids = c.add_instances(xs, True, True)
        for k, it in enumerate(items):
            tint = ((it.get('e') or {}).get('aTint')) or [1, 1, 1]; st = (it.get('e') or {}).get('aState', 0)
            for j, v in enumerate((tint[0], tint[1], tint[2], st if isinstance(st, (int, float)) else 0)): c.set_custom_data_value(k, j, float(v), False)
        ni += len(items)
    # ground under everything (lot interiors / plazas never exported as geometry)
    g = spawn(unreal.StaticMeshActor, U(128, -0.08, -128), label='GroundPlane', folder='City')
    g.static_mesh_component.set_static_mesh(load('/Engine/BasicShapes/Plane')); g.set_actor_scale3d(unreal.Vector(80, 80, 1))
    g.static_mesh_component.set_material(0, load(MAT + '/M_CityAsphalt'))
    les.save_current_level()
    log('geo level', path, len(recs), 'meshes', ni, 'instances')

def add_lighting(sun_pitch, sun_yaw, sunset=False):
    sun = spawn(unreal.DirectionalLight, unreal.Vector(0, 0, 50000), unreal.Rotator(roll=0, pitch=sun_pitch, yaw=sun_yaw), 'Sun', 'Lighting')
    lc = sun.light_component
    lc.set_editor_property('intensity', 6.0 if not sunset else 4.0)
    lc.set_editor_property('atmosphere_sun_light', True); lc.set_mobility(unreal.ComponentMobility.MOVABLE)
    spawn(unreal.SkyAtmosphere, unreal.Vector(0, 0, 0), label='SkyAtmosphere', folder='Lighting')
    sl = spawn(unreal.SkyLight, unreal.Vector(0, 0, 2000), label='SkyLight', folder='Lighting')
    sl.light_component.set_editor_property('real_time_capture', True); sl.light_component.set_mobility(unreal.ComponentMobility.MOVABLE)
    fog = spawn(unreal.ExponentialHeightFog, unreal.Vector(0, 0, 0), label='HeightFog', folder='Lighting')
    fc = fog.component; fc.set_editor_property('fog_density', 0.0025 if not sunset else 0.004); fc.set_editor_property('fog_height_falloff', 0.2)
    spawn(unreal.VolumetricCloud, unreal.Vector(0, 0, 0), label='Clouds', folder='Lighting')
    ppv = spawn(unreal.PostProcessVolume, unreal.Vector(0, 0, 0), label='PPV', folder='Lighting')
    ppv.set_editor_property('unbound', True)
    st = ppv.get_editor_property('settings')  # simple, deterministic exposure for the city test maps (P4 owns the final look)
    for k, v in (('auto_exposure_method', unreal.AutoExposureMethod.AEM_MANUAL), ('auto_exposure_bias', 2.0 if not sunset else 2.3),
                 ('auto_exposure_apply_physical_camera_exposure', False)):
        st.set_editor_property('override_' + k, True); st.set_editor_property(k, v)
    ppv.set_editor_property('settings', st)

if 'map' in STEPS:
    unreal.EditorAssetLibrary.make_directory(TESTS)
    build_geo_level(TESTS + '/City_Midtown_Geo')
    # playable test map: geometry (streamed, always loaded) + day light + PlayerStart on the 5th-Avenue-like crosswalk
    for mp, sun, cam in [('City_Midtown', (-42, 135), None)] + [(f'City_View_{s["id"]}', tuple(s.get('sun', (-42, 135))), s) for s in SHOTS]:
        world = open_level(f'{TESTS}/{mp}')
        if not any('City_Midtown_Geo' in l.get_path_name() for l in unreal.EditorLevelUtils.get_levels(world)):
            unreal.EditorLevelUtils.add_level_to_world(world, TESTS + '/City_Midtown_Geo', unreal.LevelStreamingAlwaysLoaded)
        if not les.set_current_level_by_name(mp): log('WARN could not make persistent level current', mp)  # new actors go to the persistent level, not the streamed geometry
        add_lighting(sun[0], sun[1], sunset=bool(cam and cam.get('sunset')))
        ps = SHOTS[0]['player'] if cam is None else cam.get('player', SHOTS[0]['player'])
        spawn(unreal.PlayerStart, U(ps[0], ps[1] + 1.0, ps[2]), unreal.Rotator(0, 0, -90), 'PlayerStart')
        if cam:
            p, t = U(*cam['pos']), U(*cam['target'])
            ca = spawn(unreal.CameraActor, p, look_rot(p, t), 'ShotCam_' + cam['id'])
            ca.camera_component.set_editor_property('field_of_view', cam.get('fov', 70))
            ca.camera_component.set_editor_property('constrain_aspect_ratio', False)
            ca.set_editor_property('auto_activate_for_player', unreal.AutoReceiveInput.PLAYER0)
        unreal.EditorLoadingAndSavingUtils.save_map(world, f'{TESTS}/{mp}')
        log('map', mp)
log('DONE')
